Addressing PR Comments

diff --git a/packaging/aznfs/DEBIAN/postrm b/packaging/aznfs/DEBIAN/postrm
--- a/packaging/aznfs/DEBIAN/postrm
+++ b/packaging/aznfs/DEBIAN/postrm
@@ -1,8 +1,10 @@
 #!/bin/bash
 
-# Exit on error.
-set -e
+chattr -if /opt/microsoft/aznfs/mountmap
 
-chattr -i /opt/microsoft/aznfs/mountmap
 rm -r /opt/microsoft/aznfs
-echo "Cleaned /opt/microsoft/aznfs directory."
+if [ $? -ne 0 ]; then
+	echo "Failed to clean [/opt/microsoft/aznfs]!"
+else
+	echo "Cleaned [/opt/microsoft/aznfs] directory."
+fi
diff --git a/packaging/aznfs/DEBIAN/preinst b/packaging/aznfs/DEBIAN/preinst
--- a/packaging/aznfs/DEBIAN/preinst
+++ b/packaging/aznfs/DEBIAN/preinst
@@ -2,3 +2,9 @@
 
 # Exit on error.
 set -e
+
+init="$(ps -q 1 -o comm=)"
+if [ "$init" != "systemd" ]; then
+	echo "Cannot install this package on a non-systemd system!"
+	exit 1
+fi
