Adding dependencies in control file.

diff --git a/packaging/aznfs/DEBIAN/postinst b/packaging/aznfs/DEBIAN/postinst
--- a/packaging/aznfs/DEBIAN/postinst
+++ b/packaging/aznfs/DEBIAN/postinst
@@ -1,1 +1,16 @@
 #!/bin/bash
+
+# Exit on error.
+set -e
+
+echo "===== postinst called. ====="
+
+chmod +x /sbin/aznfswatchdog
+chmod u+s,+x /sbin/mount.aznfs
+
+systemctl daemon-reload
+systemctl enable aznfswatchdog
+systemctl start aznfswatchdog
+systemctl status aznfswatchdog
+
+echo "===== postinst done. ====="
diff --git a/packaging/aznfs/DEBIAN/postrm b/packaging/aznfs/DEBIAN/postrm
--- a/packaging/aznfs/DEBIAN/postrm
+++ b/packaging/aznfs/DEBIAN/postrm
@@ -1,1 +1,8 @@
 #!/bin/bash
+
+# Exit on error.
+set -e
+
+echo "===== postrm called. ====="
+
+echo "===== postrm called. ====="
diff --git a/packaging/aznfs/DEBIAN/preinst b/packaging/aznfs/DEBIAN/preinst
--- a/packaging/aznfs/DEBIAN/preinst
+++ b/packaging/aznfs/DEBIAN/preinst
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-sudo apt-get install -y conntrack
-sudo apt-get install -y iptables
-sudo apt-get install -y systemd
-sudo apt-get install -y bind9-host
-sudo apt-get install -y iproute2
-sudo apt-get install -y util-linux
+# Exit on error.
+set -e
+
+echo "===== preinst called. ====="
+
+echo "===== preinst done. ====="
