update

diff --git a/packaging/aznfs/DEBIAN/postinst b/packaging/aznfs/DEBIAN/postinst
--- a/packaging/aznfs/DEBIAN/postinst
+++ b/packaging/aznfs/DEBIAN/postinst
@@ -49,17 +49,28 @@ if [ ! -f /opt/microsoft/aznfs/data/config ]; then
 fi
 flag_file="/tmp/.update_in_progress_from_watchdog.flag"
 
-# AUTO_UPDATE_AZNFS is set to false or not set; ask the user if they want to auto-update.
-if dialog --yesno "Do you want to auto-update AZNFS?" 10 30; then
+# # AUTO_UPDATE_AZNFS is set to false or not set; ask the user if they want to auto-update.
+# if dialog --yesno "Do you want to auto-update AZNFS?" 10 30; then
 
-        # Set AUTO_UPDATE_AZNFS to true in the config file.
-        echo "AUTO_UPDATE_AZNFS=true"
+#         # Set AUTO_UPDATE_AZNFS to true in the config file.
+#         echo "AUTO_UPDATE_AZNFS=true"
 
+# else
+#         # User chose "No"
+#         # Set AUTO_UPDATE_AZNFS to false in the config file.
+#         echo "AUTO_UPDATE_AZNFS=false"
+# fi
+
+# Display a message box with an OK button.
+dialog --msgbox "This is a message to the user." 10 30
+
+# Check the exit status to determine if the OK button was pressed.
+if [ $? -eq 0 ]; then
+    echo "OK button was pressed."
 else
-        # User chose "No"
-        # Set AUTO_UPDATE_AZNFS to false in the config file.
-        echo "AUTO_UPDATE_AZNFS=false"
+    echo "Dialog was canceled."
 fi
+
 
 # If it's an auto update triggered by aznfswatchdog, don't restart watchdog.
 if [ ! -f "$flag_file" ]; then
