Addressed comments

diff --git a/packaging/aznfs/DEBIAN/postinst b/packaging/aznfs/DEBIAN/postinst
--- a/packaging/aznfs/DEBIAN/postinst
+++ b/packaging/aznfs/DEBIAN/postinst
@@ -11,6 +11,15 @@ set -e
 FLAG_FILE="/tmp/.update_in_progress_from_watchdog.flag"
 CONFIG_FILE="/opt/microsoft/aznfs/data/config"
 AUTO_UPDATE_AZNFS="false"
+INSTALLED_STUNNEL_VERSION="0"
+REQUIRED_STUNNEL_VERSION="5.73"
+
+cleanup_stunnel_files()
+{
+    cd -
+    rm -rf /tmp/$stunnel_dir
+    rm -f /tmp/stunnel-5.73.tar.gz
+}
 
 install_stunnel()
 {
@@ -35,18 +44,14 @@ install_stunnel()
     ./configure
     if [ $? -ne 0 ]; then
         echo "Failed to configure the build. Please install stunnel and try again."
-        cd -
-        rm -rf /tmp/$stunnel_dir
-        rm -f /tmp/stunnel-5.73.tar.gz
+        cleanup_stunnel_files
         exit 1
     fi
 
     make
     if [ $? -ne 0 ]; then
         echo "Failed to build stunnel. Please install stunnel and try again."
-        cd -
-        rm -rf /tmp/$stunnel_dir
-        rm -f /tmp/stunnel-5.73.tar.gz
+        cleanup_stunnel_files
         exit 1
     fi
 
@@ -55,16 +60,12 @@ install_stunnel()
     make install
     if [ $? -ne 0 ]; then
         echo "Failed to install stunnel. Please install stunnel and try again."
-        cd -
-        rm -rf /tmp/$stunnel_dir
-        rm -f /tmp/stunnel-5.73.tar.gz
+        cleanup_stunnel_files
         exit 1
     fi
-    cd -
-    rm -rf /tmp/$stunnel_dir
-    rm -f /tmp/stunnel-5.73.tar.gz
 
-    sudo ln -s /usr/local/bin/stunnel /bin/stunnel
+    cleanup_stunnel_files
+    sudo ln -sf /usr/local/bin/stunnel /bin/stunnel
 }
 
 parse_user_config()
@@ -130,7 +131,13 @@ chmod 4755 /sbin/mount.aznfs
 mkdir -p /opt/microsoft/aznfs/data
 chmod 0755 /opt/microsoft/aznfs/data
 
-install_stunnel
+if command -v stunnel >/dev/null 2>&1; then
+    INSTALLED_STUNNEL_VERSION=$(stunnel -version 2>&1 | grep -Eo 'stunnel [0-9]+\.[0-9]+' | awk '{print $2}')
+fi
+
+if ! command -v stunnel >/dev/null 2>&1 || (( $(echo "$REQUIRED_STUNNEL_VERSION > $INSTALLED_STUNNEL_VERSION" | bc -l) )); then
+    install_stunnel
+fi
 
 # Create log directory under /etc/stunnel to store stunnel logs
 mkdir -p /etc/stunnel/microsoft/aznfs/nfsv4_fileShare/logs
