changes for postinst

diff --git a/packaging/aznfs/DEBIAN/postinst b/packaging/aznfs/DEBIAN/postinst
--- a/packaging/aznfs/DEBIAN/postinst
+++ b/packaging/aznfs/DEBIAN/postinst
@@ -5,8 +5,69 @@
 # Licensed under the MIT License. See License.txt in the project root for license information.
 # --------------------------------------------------------------------------------------------
 
+export NCURSES_NO_UTF8_ACS=1
+
 # Exit on error.
 set -e
+
+FLAG_FILE="/tmp/.update_in_progress_from_watchdog.flag"
+CONFIG_FILE="/opt/microsoft/aznfs/data/config"
+AUTO_UPDATE_AZNFS="false"
+
+parse_user_config()
+{
+    if [ ! -f "$CONFIG_FILE" ]; then
+        echo "$CONFIG_FILE not found. Please make sure it is present."
+    fi
+
+    # Read the value of AUTO_UPDATE_AZNFS from the configuration file and convert to lowercase for easy comparison later.
+    AUTO_UPDATE_AZNFS=$(egrep -o '^AUTO_UPDATE_AZNFS[[:space:]]*=[[:space:]]*[^[:space:]]*' "$CONFIG_FILE" | tr -d '[:blank:]' | cut -d '=' -f2)
+    AUTO_UPDATE_AZNFS=${AUTO_UPDATE_AZNFS,,}
+}
+
+user_consent_for_auto_update()
+{
+    # Check the value of AUTO_UPDATE_AZNFS in the config file.
+    parse_user_config
+
+    if [ "$AUTO_UPDATE_AZNFS" == "true" ]; then
+        return 0
+    fi
+
+    # Check if dialog is installed
+    if ! command -v dialog > /dev/null; then
+        echo "Error: 'dialog' is not installed. Please install it using your package manager and try again."
+        exit 1
+    fi
+
+    # To Keep dialog box size based on screen dimensions use terminal window dimensions
+    rows=$(tput lines)
+    cols=$(tput cols)
+    height=$((rows * 30 / 100))
+    width=$((cols * 60 / 100))
+
+    title="Auto-Update Configuration"
+    auto_update_prompt="Do you wish to enable automatic updates for AZNFS to ensure you stay up-to-date with the \
+                        latest features, improvements, and security patches? We recommend enabling automatic updates \
+                        to ensure you have the best AZNFS experience. If you choose to enable automatic updates, \
+                        the AZNFS will periodically check for updates and apply them automatically."
+
+    sed -i '/AUTO_UPDATE_AZNFS/d' "$CONFIG_FILE"
+
+    # Run the dialog command and capture its exit code.
+    dialog --timeout 300 --default-button yes --title "$title" --yesno "$auto_update_prompt" $height $width > /dev/tty 2>&1
+    dialog_exit_code=$?
+    
+    # Debugging: Output the exit code
+    echo "Dialog exited with code: $dialog_exit_code"
+    if [ $dialog_exit_code -eq 0 ] || [ $dialog_exit_code -eq 255 ]; then
+        # User chose "Yes" or it timed out (consider it as "true")
+        echo "AUTO_UPDATE_AZNFS=true" > "$CONFIG_FILE"
+    else
+        # User chose "No"
+        echo "AUTO_UPDATE_AZNFS=false" > "$CONFIG_FILE"
+    fi
+}
 
 # Set appropriate permissions.
 chmod 0755 /opt/microsoft/aznfs/
@@ -41,21 +102,22 @@ fi
 
 # Check if the config file exists; if not, create it.
 if [ ! -f /opt/microsoft/aznfs/data/config ]; then
-        # Create the config file and set default AUTO_UPDATE_AZNFS=true inside it.
-        echo "AUTO_UPDATE_AZNFS=true" > /opt/microsoft/aznfs/data/config
+        # Create the config file and set default AUTO_UPDATE_AZNFS=false inside it.
+        echo "AUTO_UPDATE_AZNFS=false" > /opt/microsoft/aznfs/data/config
 
         # Set the permissions for the config file.
         chmod 0644 /opt/microsoft/aznfs/data/config
 fi
-flag_file="/tmp/.update_in_progress_from_watchdog.flag"
 
 # If it's an auto update triggered by aznfswatchdog, don't restart watchdog.
-if [ ! -f "$flag_file" ]; then
+if [ ! -f "$FLAG_FILE" ]; then
+
+        user_consent_for_auto_update
+
         systemctl daemon-reload
         systemctl enable aznfswatchdog
         systemctl start aznfswatchdog
 else
         # Clean up the update in progress flag file.
-        rm -f "$flag_file"
+        rm -f "$FLAG_FILE"
 fi
-
