Personal/sroghanchi/fix nfsv4 bugs (#143)
* Init

* Add mount timeout

* Start stunnel if pid file is missing

* Fix race condition for multiple mounts

* Enable nfs-client.target

* Added ciphersuites for mariner

* Address comments

* Updated tls and notls mount logic

* Lock mountmap file

* Alternative for clean optiony

* Revert "Alternative for clean optiony"

This reverts commit aab0f19c6e10967b91128b3878396988369bc5d4.

* One stunnel process per IP

* Updated mountmap locking

* Stunnel package

* Centos7

* Install stunnel from source

* Fixed bug for privatelink

* Addressed comments

* fixed a bug

* Addressed comments

---------

Co-authored-by: Sepideh Roghanchi <sroghanchi@microsoft.com>

diff --git a/packaging/aznfs/DEBIAN/postinst b/packaging/aznfs/DEBIAN/postinst
--- a/packaging/aznfs/DEBIAN/postinst
+++ b/packaging/aznfs/DEBIAN/postinst
@@ -11,6 +11,70 @@ set -e
 FLAG_FILE="/tmp/.update_in_progress_from_watchdog.flag"
 CONFIG_FILE="/opt/microsoft/aznfs/data/config"
 AUTO_UPDATE_AZNFS="false"
+INSTALLED_STUNNEL_VERSION="0"
+REQUIRED_STUNNEL_VERSION="5.73"
+
+cleanup_stunnel_files()
+{
+    cd -
+    rm -rf /tmp/stunnel-${REQUIRED_STUNNEL_VERSION}
+    rm -f /tmp/stunnel-${REQUIRED_STUNNEL_VERSION}.tar.gz
+}
+
+install_stunnel()
+{
+    # Install stunnel package from source
+    wget https://www.stunnel.org/archive/5.x/stunnel-${REQUIRED_STUNNEL_VERSION}.tar.gz -P /tmp
+    if [ $? -ne 0 ]; then
+        echo "Failed to download stunnel source code. Please install stunnel and try again."
+        exit 1
+    fi
+
+    tar -xvf /tmp/stunnel-${REQUIRED_STUNNEL_VERSION}.tar.gz -C /tmp
+    if [ $? -ne 0 ]; then
+        echo "Failed to extract stunnel tarball. Please install stunnel and try again."
+        cleanup_stunnel_files
+        exit 1
+    fi
+
+    cd /tmp/stunnel-${REQUIRED_STUNNEL_VERSION}
+    ./configure
+    if [ $? -ne 0 ]; then
+        echo "Failed to configure the build. Please install stunnel and try again."
+        cleanup_stunnel_files
+        exit 1
+    fi
+
+    make
+    if [ $? -ne 0 ]; then
+        echo "Failed to build stunnel. Please install stunnel and try again."
+        cleanup_stunnel_files
+        exit 1
+    fi
+
+    # Install stunnel to /usr/local/bin
+    make install
+    if [ $? -ne 0 ]; then
+        echo "Failed to install stunnel. Please install stunnel and try again."
+        cleanup_stunnel_files
+        exit 1
+    fi
+
+    cleanup_stunnel_files
+
+    # Remove the old link and create a symlink to stunnel binary.
+    [ -f /bin/stunnel ] && mv /bin/stunnel /bin/stunnel.old
+    ln -sf /usr/local/bin/stunnel /bin/stunnel
+
+    if command -v stunnel >/dev/null 2>&1; then
+        echo "Successfully installed stunnel version ${REQUIRED_STUNNEL_VERSION}"
+        rm -f /bin/stunnel.old
+    else
+        echo "Failed to install stunnel version ${REQUIRED_STUNNEL_VERSION}. Please install stunnel and try again."
+        mv /bin/stunnel.old /bin/stunnel > /dev/null 2>&1
+        exit 1
+    fi
+}
 
 parse_user_config()
 {
@@ -75,6 +139,17 @@ chmod 4755 /sbin/mount.aznfs
 mkdir -p /opt/microsoft/aznfs/data
 chmod 0755 /opt/microsoft/aznfs/data
 
+if command -v stunnel >/dev/null 2>&1; then
+    INSTALLED_STUNNEL_VERSION=$(stunnel -version 2>&1 | grep -Eo 'stunnel [0-9]+\.[0-9]+' | awk '{print $2}')
+fi
+
+# Install stunnel if not present or if the installed version is older than the required version.
+if (( $(echo $REQUIRED_STUNNEL_VERSION $INSTALLED_STUNNEL_VERSION | awk '{if ($1 > $2) print 1;}') )) ; then
+    install_stunnel
+else
+    echo "stunnel version ${INSTALLED_STUNNEL_VERSION} is already installed."
+fi
+
 # Create log directory under /etc/stunnel to store stunnel logs
 mkdir -p /etc/stunnel/microsoft/aznfs/nfsv4_fileShare/logs
 chmod 0644 /etc/stunnel/microsoft/aznfs/nfsv4_fileShare/logs
@@ -111,6 +186,9 @@ fi
 #
 if [ ! -f "$FLAG_FILE" ]; then
         user_consent_for_auto_update
+
+        # Wanted by watchdog service
+        systemctl enable nfs-client.target
 
         # Start the watchdog service for NFSv3
         systemctl daemon-reload
diff --git a/src/aznfswatchdogv4 b/src/aznfswatchdogv4
--- a/src/aznfswatchdogv4
+++ b/src/aznfswatchdogv4
@@ -9,6 +9,8 @@
 # Watchdog for monitoring unmounts and stunnel processes
 #
 
+mtime_mountmap=0
+
 #
 # Kill stunnel process and clean up stunnel files generated by aznfs mount helper
 #
@@ -17,12 +19,15 @@ cleanup_stunnel_files()
     local l_conf=$1
     local l_log=$2
     local l_pid=$3
+    local accept_port
 
     # Kill stunnel process first.
     pid=$(cat $l_pid)
+    accept_port=$(cat $l_conf | grep accept | cut -d ':' -f 2)
+    pecho "killing stunnel process with pid: $pid on port: $accept_port"
     kill -9 $pid
     if [ $? -ne 0 ]; then
-        eecho "[FATAL] Unable to kill stunnel process $pid!"
+        eecho "Unable to kill stunnel process $pid!"
     fi
 
     # Cleanup stunnel files
@@ -48,57 +53,92 @@ cleanup_stunnel_files()
 #
 ensure_mountmapv4_not_exist()
 {
-    (
-        flock -e 999
-
-        #
-        # If watchdog wants to delete the entry only if MOUNTMAPv4 has not changed since
-        # watchdog looked up, honour that.
-        #
-        local ifmatch="$2"
-        if [ -n "$ifmatch" ]; then
-            local mtime=$(stat -c%Y $MOUNTMAPv4)
-            if [ "$mtime" != "$ifmatch" ]; then
-                eecho "[$1] Refusing to remove from ${MOUNTMAPv4} as $mtime != $ifmatch!"
-                return 1
-            fi
-        fi
-
-        chattr -f -i $MOUNTMAPv4
-        #
-        # We overwrite the file instead of inplace update by sed as that has a
-        # very bad side-effect of creating a new MOUNTMAPv4 file. This breaks
-        # any locking that we dependent on the old file.
-        #
-        out=$(sed "\%^${1}$%d" $MOUNTMAPv4)
-        ret=$?
-        if [ $ret -eq 0 ]; then
-            #
-            # If this echo fails then MOUNTMAPv4 could be truncated.
-            #
-            echo "$out" > $MOUNTMAPv4
-            ret=$?
-            out=
-            if [ $ret -ne 0 ]; then
-                eecho "*** [FATAL] MOUNTMAPv4 may be in inconsistent state, contact Microsoft support ***"
-            fi
-        fi
-
-        if [ $ret -ne 0 ]; then
-            chattr -f +i $MOUNTMAPv4
-            eecho "[$1] failed to remove from ${MOUNTMAPv4}!"
+    #
+    # If watchdog wants to delete the entry only if MOUNTMAPv4 has not changed since
+    # watchdog looked up, honour that.
+    #
+    local mountmap_mtime="$2"
+    if [ -n "$mountmap_mtime" ]; then
+        local mtime=$(stat -c%Y $MOUNTMAPv4)
+        if [ "$mtime" != "$mountmap_mtime" ]; then
+            eecho "[$1] Refusing to remove from ${MOUNTMAPv4} as $mtime != $mountmap_mtime!"
             return 1
         fi
-        chattr -f +i $MOUNTMAPv4
+    fi
 
-        # Return the mtime after our mods.
-        echo $(stat -c%Y $MOUNTMAPv4)
-    ) 999<$MOUNTMAPv4
+    chattr -f -i $MOUNTMAPv4
+    #
+    # We overwrite the file instead of inplace update by sed as that has a
+    # very bad side-effect of creating a new MOUNTMAPv4 file. This breaks
+    # any locking that we dependent on the old file.
+    #
+    out=$(sed "\%^${1}$%d" $MOUNTMAPv4)
+    ret=$?
+    if [ $ret -eq 0 ]; then
+        #
+        # If this echo fails then MOUNTMAPv4 could be truncated.
+        #
+        echo "$out" > $MOUNTMAPv4
+        ret=$?
+        out=
+        if [ $ret -ne 0 ]; then
+            eecho "*** [FATAL] MOUNTMAPv4 may be in inconsistent state, contact Microsoft support ***"
+        fi
+    fi
+
+    chattr -f +i $MOUNTMAPv4
+
+    if [ $ret -ne 0 ]; then
+        eecho "[$1] failed to remove from ${MOUNTMAPv4}!"
+        return 1
+    fi
+
+    pecho "[$1] removed from ${MOUNTMAPv4} successfully!"
+
+    # Return the mtime after our mods.
+    echo $(stat -c%Y $MOUNTMAPv4)
+}
+
+cleanup_mount()
+{
+    local l_conf=$1
+    local l_log=$2
+    local l_pid=$3
+    local line=$4
+
+    # Need to lock MOUNTMAPv4 since the mountscript could modify them as well.
+    exec {fd2}<$MOUNTMAPv4
+    flock -e $fd2
+
+    # Delete IFF mountmap is not changed since we read it above.
+    l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
+
+    #
+    # Update mountmap mtime in case of successful updation of MOUNTMAPv4,
+    # so that we can distinguish between MOUNTMAPv4 mtime changing because
+    # of our action or some mount helper changing it. In the former case
+    # it's safe to update the MOUNTMAPv4, so update mtime_mountmap to the
+    # mtime after this update.
+    #
+    if [ $? -eq 0 ]; then
+        mtime_mountmap=$l_mtime
+    else
+        # If the mountmap file is changed since we read it, we need to read it again - don't modify anything.
+        eecho "Failed to delete entry from ${MOUNTMAPv4}! Entry: [$line]"
+        flock -u $fd2
+        exec {fd2}<&-
+        return 1
+    fi
+
+    cleanup_stunnel_files $l_conf $l_log $l_pid
+
+    flock -u $fd2
+    exec {fd2}<&-
+    return 0
 }
 
 process_nfsv4_mounts()
 {
-    local l_host
     local l_conf
     local l_log
     local l_pid
@@ -142,6 +182,11 @@ process_nfsv4_mounts()
         exit 1
     fi
 
+    if [ -z "$NETSTATCOMMAND" ]; then
+        eecho "[FATAL] No socket statistics command (netstat or ss) found! Aznfswatchdogv4 service is exiting. Please contact Microsoft support"
+        exit 1
+    fi
+
     for line in $lines; do
         if [ -z "$line" ]; then
             continue
@@ -149,19 +194,34 @@ process_nfsv4_mounts()
 
         #
         # MOUNTMAPv4 line is of the form:
-        # account.file.preprod.core.windows.net;<stunnel_account.file.preprod.core.windows.net.conf path>;<stunnel_account.file.preprod.core.windows.net.log path>;<stunnel_account.file.preprod.core.windows.net.pid path>;<checksumHash>
+        # <IP>;<stunnel_account.file.preprod.core.windows.net.conf path>;<stunnel_account.file.preprod.core.windows.net.log path>;<stunnel_account.file.preprod.core.windows.net.pid path>;<checksumHash>;<status>;<timeout>
         #
-        IFS=";" read l_host l_conf l_log l_pid l_checksumhash <<< "$line"
+        IFS=";" read l_ip l_conf l_log l_pid l_checksumhash l_status l_timeout <<< "$line"
 
-        if [ -z "$l_host" -o -z "$l_conf" -o -z "$l_pid" ]; then
+        if [ -z "$l_ip" -o -z "$l_conf" -o -z "$l_pid" ]; then
             wecho "[FATAL] Deleting invalid line in $MOUNTMAPv4: [$line]!"
+            exec {fd2}<$MOUNTMAPv4
+            flock -e $fd2
             l_mtime=$(ensure_mountmapv4_not_exist "$line")
             [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            flock -u $fd2
+            exec {fd2}<&-
             continue
         fi
 
+        # Skip if the status is waiting, which means the mountscript is still processing the mount.
+        if [ "$l_status" == "waiting" ]; then
+            # vecho "Skipping entry with status 'waiting': [$line]"
+            if [[ $l_timeout -ge $(date +%s) ]]; then
+                # Timeout is in future, skip this entry.
+                # If a mount entry stays in the 'waiting' state for a long time (grater than the mount timeout), it's safe to clean it up.
+                # vecho "Timeout is in future, skipping entry with status 'waiting': [$line]"
+                continue
+            fi
+        fi
+
         accept_port=$(cat $l_conf | grep accept | cut -d ':' -f 2)
-        vecho "accept_port: $accept_port"
+        # vecho "accept_port: $accept_port"
 
         #
         # Delete entry from MOUNTMAPv4 if there are no mounted shares on that host.
@@ -169,23 +229,13 @@ process_nfsv4_mounts()
         # it around.
         #
         if ! echo "$findmnt" | grep "$accept_port" >/dev/null; then
-            pecho "No mounted shares for host $l_host, deleting from ${MOUNTMAPv4} [$line]."
+            pecho "No mounted shares for host $l_ip with accept port $accept_port, deleting from ${MOUNTMAPv4} [$line]."
 
-            cleanup_stunnel_files $l_conf $l_log $l_pid
-
-            # Delete IFF mountmap is not changed since we read it above.
-            l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
-
-            #
-            # Update ifmatch time in case of successful updation of MOUNTMAPv4,
-            # so that we can distinguish between MOUNTMAPv4 mtime changing because
-            # of our action or some mount helper changing it. In the former case
-            # it's safe to update the MOUNTMAPv4, so update mtime_mountmap to the
-            # mtime after this update.
-            #
-            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            cleanup_mount $l_conf $l_log $l_pid $line
             continue
         else
+            # vecho "Mounted shares found for host $l_ip with accept port $accept_port."
+
             # Check if checksumHash for stunnel.conf file has changed.
             # Customers should not modify stunnel.conf files created by aznfs mount helper.
             checksumHash=`cksum $l_conf | awk '{print $1}'`
@@ -197,19 +247,15 @@ process_nfsv4_mounts()
                 eecho "'${l_conf}' file has modified!"
                 eecho "It's not recommended to modify '${l_conf}' file created by aznfs mount helper!"
                 eecho "watchdog service will do cleanup, kill stunnel process with pid:$(cat $l_pid) and remove '${l_conf}'; '${l_log}'; '${l_pid}'!"
-                eecho "Please remount the shares from ${l_host} using aznfs mount helper."
+                eecho "Please remount the shares from ${l_ip} using aznfs mount helper."
 
-                cleanup_stunnel_files $l_conf $l_log $l_pid
-
-                # Delete IFF mountmap is not changed since we read it above.
-                l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
-                [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+                cleanup_mount $l_conf $l_log $l_pid $line
                 continue
             fi
 
-            is_stunnel_running=$(netstat -anp | grep stunnel | grep `cat $l_pid`)
+            is_stunnel_running=$($NETSTATCOMMAND -anp | grep stunnel | grep `cat $l_pid`)
             if [ -z "$is_stunnel_running" ]; then
-                vecho "stunnel is not running! Restarting the stunnel"
+                vecho "Watchdog: stunnel is not running! Restarting the stunnel"
 
                 stunnel_status=$(stunnel $l_conf 2>&1)
                 if [ -n "$stunnel_status" ]; then
@@ -218,19 +264,17 @@ process_nfsv4_mounts()
                     is_caroot_cert_failure=$(echo $stunnel_status | grep "certificate verify failed")
                     if [ -n "$is_binding_error" ]; then
                         eecho "[FATAL] Restarting stunnel failed.$used_port port is already being used by other process.!"
-                        eecho "It's recommended to unmount all shares from $l_host and then remount shares using aznfs mount helper!"
+                        eecho "It's recommended to unmount all shares from $l_ip and then remount shares using aznfs mount helper!"
                     elif [ -n "$is_caroot_cert_failure" ]; then
                         eecho "[FATAL] Restarting stunnel failed. CA root certificate is either missing or is unable to authenticate TLS server certificate."
                         eecho "Please download the CA root certificate from https://learn.microsoft.com/en-us/azure/security/fundamentals/azure-ca-details"
-                        eecho "It's recommended to unmount all shares from $l_host and then remount shares using aznfs mount helper!"
+                        eecho "It's recommended to unmount all shares from $l_ip and then remount shares using aznfs mount helper!"
                     else
                         eecho "[FATAL] watchdog service is unable to start stunnel process for '${l_conf}'!"
                         eecho "Please check the stunnel logs in $l_log for more details."
-                        eecho "It's recommended to unmount all shares from $l_host and then remount shares using aznfs mount helper!"
+                        eecho "It's recommended to unmount all shares from $l_ip and then remount shares using aznfs mount helper!"
                     fi
                 fi
-            else
-                vecho "stunnel is running!!"
             fi
         fi
     done
