running only systemctl enable when systemd installed and not booted

diff --git a/packaging/aznfs/DEBIAN/postinst b/packaging/aznfs/DEBIAN/postinst
--- a/packaging/aznfs/DEBIAN/postinst
+++ b/packaging/aznfs/DEBIAN/postinst
@@ -35,6 +35,24 @@ chattr +i /opt/microsoft/aznfs/randbytes
 set -e
 
 # Start aznfswatchdog service.
-systemctl daemon-reload
-systemctl enable aznfswatchdog
-systemctl start aznfswatchdog
+init="$(ps -q 1 -o comm=)"
+if [ "$init" != "systemd" ]; then
+	#
+	# For containers, we may have systemd installed but not booted yet.
+	# Allow installation as long as systemd is installed.
+	#
+	echo "init is not systemd, checking if systemd is installed!"
+	if [ ! -x /lib/systemd/systemd ]; then
+		echo "systemd is not installed!"
+		echo "Cannot install aznfs on a non-systemd system!"
+		exit 1
+	fi
+
+	echo "OK, systemd installed, but not booted, continuing installation!"
+	systemctl enable aznfswatchdog
+else
+	echo "System is booted with systemd, continuing installation!"
+	systemctl daemon-reload
+	systemctl enable aznfswatchdog
+	systemctl start aznfswatchdog
+fi
