update

diff --git a/packaging/aznfs/DEBIAN/postinst b/packaging/aznfs/DEBIAN/postinst
--- a/packaging/aznfs/DEBIAN/postinst
+++ b/packaging/aznfs/DEBIAN/postinst
@@ -33,50 +33,57 @@ user_consent_for_auto_update()
     if [ "$AUTO_UPDATE_AZNFS" == "true" ]; then
         return 0
     fi
-#*******************************************************************************************************
-#     # Get the terminal window dimensions
-#     rows=$(tput lines)
-#     cols=$(tput cols)
 
-#     # To Keep dialog box size based on screen dimensions
-#     height=$((rows * 30 / 100))
-#     width=$((cols * 60 / 100))
-
-#     title="Auto-Update Configuration"
-#     auto_update_prompt="Do you wish to enable automatic updates for AZNFS to ensure you stay up-to-date with the \
-#                         latest features, improvements, and security patches? We recommend enabling automatic updates \
-#                         to ensure you have the best AZNFS experience. If you choose to enable automatic updates, \
-#                         the AZNFS will periodically check for updates and apply them automatically."
-
-#     sed -i '/AUTO_UPDATE_AZNFS/d' "$CONFIG_FILE"
-
-#     # Run the dialog command and capture its exit code.
-#     dialog --timeout 300 --default-button yes --title "$title" --yesno "$auto_update_prompt" $height $width
-#     dialog_exit_code=$?
-
-#     if [ $dialog_exit_code -eq 0 ] || [ $dialog_exit_code -eq 255 ]; then
-#         # User chose "Yes" or it timed out (consider it as "true")
-#         echo "AUTO_UPDATE_AZNFS=true" > "$CONFIG_FILE"
-#     else
-#         # User chose "No"
-#         echo "AUTO_UPDATE_AZNFS=false" > "$CONFIG_FILE"
-#     fi
 #*******************************************************************************************************
 
-# Check if dialog is installed
-if ! command -v dialog > /dev/null; then
-    echo "Error: 'dialog' is not installed. Please install it and try again."
-    exit 1
-fi
+    # Check if dialog is installed
+    if ! command -v dialog > /dev/null; then
+        echo "Error: 'dialog' is not installed. Please install it and try again."
+        exit 1
+    fi
 
-# Debugging
-echo "Before dialog"
-dialog --msgbox "I'm a dialog box message" 10 30 2>&1 > /dev/tty
-dialog_exit_code=$?
-echo "After dialog"
+    # Get the terminal window dimensions
+    rows=$(tput lines)
+    cols=$(tput cols)
 
-# Debugging: Output the exit code
-echo "Exit code: $dialog_exit_code"
+    # To Keep dialog box size based on screen dimensions
+    height=$((rows * 30 / 100))
+    width=$((cols * 60 / 100))
+
+    title="Auto-Update Configuration"
+    auto_update_prompt="Do you wish to enable automatic updates for AZNFS to ensure you stay up-to-date with the \
+                        latest features, improvements, and security patches? We recommend enabling automatic updates \
+                        to ensure you have the best AZNFS experience. If you choose to enable automatic updates, \
+                        the AZNFS will periodically check for updates and apply them automatically."
+
+    sed -i '/AUTO_UPDATE_AZNFS/d' "$CONFIG_FILE"
+
+    # Run the dialog command and capture its exit code.
+    dialog --timeout 300 --default-button yes --title "$title" --yesno "$auto_update_prompt" $height $width 2>&1 > /dev/tty
+    dialog_exit_code=$?
+    
+    # Debugging: Output the exit code
+    echo "Exit code: $dialog_exit_code"
+    if [ $dialog_exit_code -eq 0 ] || [ $dialog_exit_code -eq 255 ]; then
+        # User chose "Yes" or it timed out (consider it as "true")
+        echo "AUTO_UPDATE_AZNFS=true" > "$CONFIG_FILE"
+    else
+        # User chose "No"
+        echo "AUTO_UPDATE_AZNFS=false" > "$CONFIG_FILE"
+    fi
+
+    echo "After dialog"
+    
+#*******************************************************************************************************
+
+# # Debugging
+# echo "Before dialog"
+# dialog --msgbox "I'm a dialog box message" 10 30 2>&1 > /dev/tty
+# dialog_exit_code=$?
+# echo "After dialog"
+
+# # Debugging: Output the exit code
+# echo "Exit code: $dialog_exit_code"
 }
 
 # Set appropriate permissions.
