Added detailed logs for stunnel restart failures

diff --git a/src/azfilenfs-watchdog b/src/azfilenfs-watchdog
--- a/src/azfilenfs-watchdog
+++ b/src/azfilenfs-watchdog
@@ -12,6 +12,12 @@
 MONITOR_INTERVAL_SECS=5
 
 #
+# Remove unmounted entries only if MOUNTMAP has not been changed till MONITOR_INTERVAL_SECS seconds.
+# Don't set it below 3 minutes.
+#
+MOUNTMAP_INACTIVITY_SECS=300
+
+#
 # Don't perform mountmap and iptables rule cleanup for unmounted filesystems.
 # This can be set if you want lazy umount to work.
 #
@@ -19,7 +25,7 @@ AZNFS_SKIP_UNMOUNT_CLEANUP="${AZNFS_SKIP_UNMOUNT_CLEANUP:-0}"
 
 # Load common aznfs helpers.
 . /opt/microsoft/aznfs/common.sh
-AZ_FILES_MOUNTMAP="$OPTDIR/aznfs_files_mountmap"
+LOCALHOST="127.0.0.1"
 
 
 #
@@ -76,14 +82,45 @@ ensure_az_files_mountmap_not_exist()
 }
 
 
+#
+# Kill stunnel process and clean up stunnel files generated by aznfs mount helper
+#
+cleanupStunnelFiles()
+{
+    # Kill stunnel process first.
+    pid=$(cat $l_pid)
+    kill -9 $pid
+    if [ $? -ne 0 ]; then
+        eecho "[FATAL] Unable to kill stunnel process '$pid'!"
+    fi
+
+    # Cleanup stunnel files
+    rm $l_log
+    if [ $? -ne 0 ]; then
+        eecho "[FATAL] Unable to delete stunnel log file $l_log!"
+    fi
+
+    rm $l_pid
+    if [ $? -ne 0 ]; then
+        eecho "[FATAL] Unable to delete stunnel pid file $l_pid!"
+    fi
+
+    chattr -if $l_conf
+    rm $l_conf
+    if [ $? -ne 0 ]; then
+        eecho "[FATAL] Unable to delete stunnel conf file $l_conf!"
+    fi
+}
+
+
 vecho "Starting azfilenfs-watchdog..."
 
 if [ ! -f $AZ_FILES_MOUNTMAP ]; then
-	touch $AZ_FILES_MOUNTMAP
-	if [ $? -ne 0 ]; then
-		eecho "[FATAL] Not able to create '${AZ_FILES_MOUNTMAP}'!"
-		exit 1
-	fi
+    touch $AZ_FILES_MOUNTMAP
+    if [ $? -ne 0 ]; then
+        eecho "[FATAL] Not able to create '${AZ_FILES_MOUNTMAP}'!"
+        exit 1
+    fi
 fi
 
 if ! chattr -f +i $AZ_FILES_MOUNTMAP; then
@@ -119,7 +156,7 @@ while :; do
     # AZ_FILES_MOUNTMAP entry whose all nfs file shares are unmounted, we know
     # for sure that it's not in use by any mount and can be removed.
     #
-    findmnt=$(findmnt | grep 'nfs4\|127.0.0.1' 2>&1)
+    findmnt=$(findmnt | grep 'nfs4\|$LOCALHOST' 2>&1)
 
     #
     # For no matching mounts also, findmnt exits with a failure return, so check
@@ -153,7 +190,7 @@ while :; do
         fi
 
 	accept_port=$(cat $l_conf | grep accept | cut -d ':' -f 2)
-	echo "accept_port: $accept_port"
+	vecho "accept_port: $accept_port"
 
         #
         # Delete entry from AZ_FILES_MOUNTMAP if there are no mounted shares on that host.
@@ -161,59 +198,69 @@ while :; do
         # it around.
         #
         if ! echo "$findmnt" | grep "$accept_port" >/dev/null; then
-                pecho "No mounted shares for host $l_host, deleting from ${AZ_FILES_MOUNTMAP} [$line]."
+            pecho "No mounted shares for host $l_host, deleting from ${AZ_FILES_MOUNTMAP} [$line]."
 
-		# Kill stunnel process first.
-		pid=$(cat $l_pid)
-		kill -9 $pid
-		if [ $? -ne 0 ]; then
-		    eecho "[FATAL] Unable to kill stunnel process '$pid'!"
-		    exit 1
-		fi
+            cleanupStunnelFiles
 
-		# Cleanup stunnel files
-		rm $l_log
-		if [ $? -ne 0 ]; then
-		    eecho "[FATAL] Unable to delete stunnel log file $l_log!"
-		    exit 1
-		fi
+            # Delete IFF mountmap is not changed since we read it above.
+            l_mtime=$(ensure_az_files_mountmap_not_exist "$line" "$mtime_mountmap")
 
-		rm $l_pid
-		if [ $? -ne 0 ]; then
-		    eecho "[FATAL] Unable to delete stunnel pid file $l_pid!"
-		    exit 1
-		fi
+            #
+            # Update ifmatch time in case of successful updation of AZ_FILES_MOUNTMAP,
+            # so that we can distinguish between AZ_FILES_MOUNTMAP mtime changing because
+            # of our action or some mount helper changing it. In the former case
+            # it's safe to update the AZ_FILES_MOUNTMAP, so update mtime_mountmap to the
+            # mtime after this update.
+            #
+            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            continue
+        else
+            # check if checksumHash for stunnel.conf file has changed.
+            # Customers should not modify stunnel.conf files created by aznfs mount helper.
+            checksumHash=`cksum $l_conf | awk '{print $1}'`
+            if [ $? -ne 0 ]; then
+                eecho "Failed to get the checksum hash of file: '${l_conf}'!"
+            fi
 
-		chattr -if $l_conf
-		rm $l_conf
-		if [ $? -ne 0 ]; then
-		    eecho "[FATAL] Unable to delete stunnel conf file $l_conf!"
-		    exit 1
-		fi
+            if [ $checksumHash != $l_checksumhash ]; then
+                eecho "'${l_conf}' file has modified!"
+                eecho "It's not recommended to modify '${l_conf}' file created by aznfs mount helper!"
+                eecho "azfilenfs-watchdog service will do cleanup, kill stunnel process with pid:$(cat $l_pid) and remove '${l_conf}'; '${l_log}'; '${l_pid}'!"
+                eecho "Please remount the shares from ${l_host} using aznfs mount helper."
+
+                cleanupStunnelFiles
 
                 # Delete IFF mountmap is not changed since we read it above.
                 l_mtime=$(ensure_az_files_mountmap_not_exist "$line" "$mtime_mountmap")
-
-                #
-                # Update ifmatch time in case of successful updation of AZ_FILES_MOUNTMAP,
-                # so that we can distinguish between AZ_FILES_MOUNTMAP mtime changing because
-                # of our action or some mount helper changing it. In the former case
-                # it's safe to update the AZ_FILES_MOUNTMAP, so update mtime_mountmap to the
-                # mtime after this update.
-                #
                 [ $? -eq 0 ] && mtime_mountmap=$l_mtime
                 continue
-        else
-	    is_stunnel_running=$(netstat -anp | grep stunnel | grep `cat $l_pid`)
-	    echo "$is_stunnel_running"
-	    if [ -z "$is_stunnel_running" ]; then
+	    fi
+
+            is_stunnel_running=$(netstat -anp | grep stunnel | grep `cat $l_pid`)
+            if [ -z "$is_stunnel_running" ]; then
                 vecho "stunnel is not running! Restarting the stunnel"
 
                 stunnel_status=$(stunnel $l_conf 2>&1)
-		if [ -n "$stunnel_status" ]; then
-		    eecho "[FATAL] Not able to start stunnel process for '${l_conf}'!"
-                    exit 1
+                if [ -n "$stunnel_status" ]; then
+                    used_port=$(cat $l_conf | grep accept | cut -d: -f2)
+                    is_binding_error=$(echo $stunnel_status | grep "$LOCALHOST:$used_port: Address already in use")
+                    is_caroot_cert_failure=$(echo $stunnel_status | grep "certificate verify failed")
+                    if [ -n "$is_binding_error" ]; then
+                        eecho "[FATAL] Restarting stunnel failed.$used_port port is already being used by other process.!"
+                        eecho "It's recommended to unmount all shares from $l_host and then remount shares using aznfs mount helper!"
+                    elif [ -n "$is_caroot_cert_failure" ]; then
+                        # TODO: confirm exactly which CA root cert to download for production.
+                        eecho "[FATAL] Restarting stunnel failed. CA root certificate is either missing or is unable to authenticate TLS server certificate."
+                        eecho "Please download the CA root certificate from https://learn.microsoft.com/en-us/azure/security/fundamentals/azure-ca-details"
+                        eecho "It's recommended to unmount all shares from $l_host and then remount shares using aznfs mount helper!"
+                    else
+                        eecho "[FATAL] azfilenfs-watchdog service is unable to start stunnel process for '${l_conf}'!"
+                        eecho "Please check the stunnel logs in $l_log for more details."
+                        eecho "It's recommended to unmount all shares from $l_host and then remount shares using aznfs mount helper!"
+		    fi
 		fi
+	    else
+	        vecho "stunnel is running!!"
 	    fi
         fi
 
