Merged nfsv3 and nfsv4 watchdog in one script

diff --git a/src/aznfswatchdog b/src/aznfswatchdog
--- a/src/aznfswatchdog
+++ b/src/aznfswatchdog
@@ -12,7 +12,7 @@ RELEASE_NUMBER_FOR_AKS=x.y.z
 
 #
 # How often does the watchdog look for unmounts and/or IP address changes for
-# Blob endpoints.
+# Blob and nfs file endpoints.
 #
 MONITOR_INTERVAL_SECS=5
 
@@ -52,6 +52,8 @@ next_ip_change_detection_epoch=0
 # and ensures that updates are deferred until 1 minute after the start of the aznfswatchdog.
 #
 next_daily_run_epoch=$(expr $(date +%s) + 60)
+
+LOCALHOST="127.0.0.1"
 
 # Load common aznfs helpers.
 . /opt/microsoft/aznfs/common.sh
@@ -366,42 +368,96 @@ log_version_info()
     vecho "AZNFS version: $current_version"
 }
 
-vecho "Starting aznfswatchdog..."
-
-# Detect and log distro, bash and AZNFS-mount version
-log_version_info
-
-# Dump NAT table once on startup in case we have reported conflicts.
-vecho "NAT table:\n$(iptables-save -t nat)"
-conntrack -L > /dev/null
-
-# conntrack timewait timeout higher than the TCP timewait timeout value isn't very valuable.
-conntrack_timeo_timew=$(cat /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_time_wait 2>/dev/null)
-if [ $? -eq 0 ] && [ -n "$conntrack_timeo_timew" -a $conntrack_timeo_timew -gt $AZNFS_TIMEWAIT_TIMEOUT ]; then
-        vecho "Changing /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_time_wait [$conntrack_timeo_timew -> $AZNFS_TIMEWAIT_TIMEOUT]"
-        echo $AZNFS_TIMEWAIT_TIMEOUT > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_time_wait
-fi
-
-if ! chattr -f +i $MOUNTMAP; then
-    wecho "chattr does not work for ${MOUNTMAP}!"
-fi
 
 #
-# If we are not skipping IP change detection for regional accounts, then mountmap file will be updated every minute
-# due to the change in IP for regional account FQDN. If we use standard MOUNTMAP_INACTIVITY_SECS,
-# then this will prevent mountmap entry to be deleted. We set this to less than 1 minute in this case.
+# Delete entry from $AZ_FILES_MOUNTMAP.
 #
-if [ "$AZNFS_SKIP_IP_CHANGE_DETECTION_FOR_REGIONAL_ACCOUNTS" == "0" ]; then
-    MOUNTMAP_INACTIVITY_SECS=45
-fi
+ensure_az_files_mountmap_not_exist()
+{
+    (
+        flock -e 999
+
+        #
+        # If user wants to delete the entry only if AZ_FILES_MOUNTMAP has not changed since
+        # he looked up, honour that.
+        #
+        local ifmatch="$2"
+        if [ -n "$ifmatch" ]; then
+            local mtime=$(stat -c%Y $AZ_FILES_MOUNTMAP)
+            if [ "$mtime" != "$ifmatch" ]; then
+                eecho "[$1] Refusing to remove from ${AZ_FILES_MOUNTMAP} as $mtime != $ifmatch!"
+                return 1
+            fi
+        fi
+
+	chattr -f -i $AZ_FILES_MOUNTMAP
+        #
+        # We do this thing instead of inplace update by sed as that has a
+        # very bad side-effect of creating a new AZ_FILES_MOUNTMAP file. This breaks
+        # any locking that we dependent on the old file.
+        #
+        out=$(sed "\%^${1}$%d" $AZ_FILES_MOUNTMAP)
+        ret=$?
+        if [ $ret -eq 0 ]; then
+            #
+            # If this echo fails then AZ_FILES_MOUNTMAP could be truncated.
+            #
+            echo "$out" > $AZ_FILES_MOUNTMAP
+            ret=$?
+            out=
+            if [ $ret -ne 0 ]; then
+                eecho "*** [FATAL] AZ_FILES_MOUNTMAP may be in inconsistent state, contact Microsoft support ***"
+            fi
+        fi
+
+        if [ $ret -ne 0 ]; then
+            chattr -f +i $AZ_FILES_MOUNTMAP
+            eecho "[$1] failed to remove from ${AZ_FILES_MOUNTMAP}!"
+            return 1
+        fi
+        chattr -f +i $AZ_FILES_MOUNTMAP
+
+	# Return the mtime after our mods.
+        echo $(stat -c%Y $AZ_FILES_MOUNTMAP)
+    ) 999<$AZ_FILES_MOUNTMAP
+}
+
+#
+# Kill stunnel process and clean up stunnel files generated by aznfs mount helper
+#
+cleanupStunnelFiles()
+{
+    # Kill stunnel process first.
+    pid=$(cat $l_pid)
+    kill -9 $pid
+    if [ $? -ne 0 ]; then
+        eecho "[FATAL] Unable to kill stunnel process '$pid'!"
+    fi
+
+    # Cleanup stunnel files
+    rm $l_log
+    if [ $? -ne 0 ]; then
+        eecho "[FATAL] Unable to delete stunnel log file $l_log!"
+    fi
+
+    rm $l_pid
+    if [ $? -ne 0 ]; then
+        eecho "[FATAL] Unable to delete stunnel pid file $l_pid!"
+    fi
+
+    chattr -if $l_conf
+    rm $l_conf
+    if [ $? -ne 0 ]; then
+        eecho "[FATAL] Unable to delete stunnel conf file $l_conf!"
+    fi
+}
 
 #
 # Watchdog for monitoring unmounts and more importantly change in blob endpoint
 # addresses possibly as a result of migration.
 #
-while :; do
-    sleep $MONITOR_INTERVAL_SECS
-
+processNFS3Mounts()
+{
     #
     # TODO: Add a function reconcile_mountmap() and call it from here. This
     #       should reconstruct the MOUNTMAP file from findmnt and output of
@@ -621,5 +677,194 @@ while :; do
             fi
         fi
     done
+}
 
+#
+# Watchdog for monitoring unmounts and stunnel processes
+#
+processNFS4Mounts()
+{
+    epoch_now=$(date +%s)
+
+    #
+    # Go over all lines in $AZ_FILES_MOUNTMAP and check them for two things:
+    # 1. Is that entry still in use by at least one aznfs mount, if not remove the entry.
+    # 2. Is stunnel process running?
+    #
+    # We store the mtime of AZ_FILES_MOUNTMAP while inside the lock so that if any mount helper process
+    # updates it after this we will skip modification for sake of safety. We will come to it
+    # in the next iteration when it's safer.
+    #
+    exec {fd}<$AZ_FILES_MOUNTMAP
+    flock -e $fd
+    mtime_mountmap=$(stat -c%Y $AZ_FILES_MOUNTMAP)
+    IFS=$'\n' lines=$(cat $AZ_FILES_MOUNTMAP)
+    flock -u $fd
+    exec {fd}<&-
+
+    #
+    # findmnt must be done after reading AZ_FILES_MOUNTMAP so that if we come accross a
+    # AZ_FILES_MOUNTMAP entry whose all nfs file shares are unmounted, we know
+    # for sure that it's not in use by any mount and can be removed.
+    #
+    findmnt=$(findmnt | grep 'nfs4\|$LOCALHOST' 2>&1)
+
+    #
+    # For no matching mounts also, findmnt exits with a failure return, so check
+    # for both exit status and non-empty error o/p.
+    #
+    if [ $? -ne 0 -a -n "$findmnt" ]; then
+        eecho "${findmnt}."
+        eecho "[FATAL] findmnt failed unexpectedly!"
+        eecho "[FATAL] Azfilenfs-watchdog service is exiting, will not monitor Azure NFS file shares."
+        eecho "[FATAL] Please contact Microsoft support before using any NFS File shares."
+        # This usually indicates some non-transient issue, bail out.
+        exit 1
+    fi
+
+    for line in $lines; do
+        if [ -z "$line" ]; then
+            continue
+        fi
+
+        #
+        # AZ_FILES_MOUNTMAP line is of the form:
+        # account.file.preprod.core.windows.net;<stunnel_account.file.preprod.core.windows.net.conf path>;<stunnel_account.file.preprod.core.windows.net.log path>;<stunnel_account.file.preprod.core.windows.net.pid path>;<checksumHash>
+        #
+        IFS=";" read l_host l_conf l_log l_pid l_checksumhash <<< "$line"
+
+        if [ -z "$l_host" -o -z "$l_conf" -o -z "$l_pid" ]; then
+            wecho "[FATAL] Deleting invalid line in $AZ_FILES_MOUNTMAP: [$line]!"
+            l_mtime=$(ensure_az_files_mountmap_not_exist "$line")
+            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            continue
+        fi
+
+	accept_port=$(cat $l_conf | grep accept | cut -d ':' -f 2)
+	vecho "accept_port: $accept_port"
+
+        #
+        # Delete entry from AZ_FILES_MOUNTMAP if there are no mounted shares on that host.
+        # As long as we have at least one mount using the AZ_FILES_MOUNTMAP entry, we leave
+        # it around.
+        #
+        if ! echo "$findmnt" | grep "$accept_port" >/dev/null; then
+            pecho "No mounted shares for host $l_host, deleting from ${AZ_FILES_MOUNTMAP} [$line]."
+
+            cleanupStunnelFiles
+
+            # Delete IFF mountmap is not changed since we read it above.
+            l_mtime=$(ensure_az_files_mountmap_not_exist "$line" "$mtime_mountmap")
+
+            #
+            # Update ifmatch time in case of successful updation of AZ_FILES_MOUNTMAP,
+            # so that we can distinguish between AZ_FILES_MOUNTMAP mtime changing because
+            # of our action or some mount helper changing it. In the former case
+            # it's safe to update the AZ_FILES_MOUNTMAP, so update mtime_mountmap to the
+            # mtime after this update.
+            #
+            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            continue
+        else
+            # check if checksumHash for stunnel.conf file has changed.
+            # Customers should not modify stunnel.conf files created by aznfs mount helper.
+            checksumHash=`cksum $l_conf | awk '{print $1}'`
+            if [ $? -ne 0 ]; then
+                eecho "Failed to get the checksum hash of file: '${l_conf}'!"
+            fi
+
+            if [ $checksumHash != $l_checksumhash ]; then
+                eecho "'${l_conf}' file has modified!"
+                eecho "It's not recommended to modify '${l_conf}' file created by aznfs mount helper!"
+                eecho "azfilenfs-watchdog service will do cleanup, kill stunnel process with pid:$(cat $l_pid) and remove '${l_conf}'; '${l_log}'; '${l_pid}'!"
+                eecho "Please remount the shares from ${l_host} using aznfs mount helper."
+
+                cleanupStunnelFiles
+
+                # Delete IFF mountmap is not changed since we read it above.
+                l_mtime=$(ensure_az_files_mountmap_not_exist "$line" "$mtime_mountmap")
+                [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+                continue
+	    fi
+
+            is_stunnel_running=$(netstat -anp | grep stunnel | grep `cat $l_pid`)
+            if [ -z "$is_stunnel_running" ]; then
+                vecho "stunnel is not running! Restarting the stunnel"
+
+                stunnel_status=$(stunnel $l_conf 2>&1)
+                if [ -n "$stunnel_status" ]; then
+                    used_port=$(cat $l_conf | grep accept | cut -d: -f2)
+                    is_binding_error=$(echo $stunnel_status | grep "$LOCALHOST:$used_port: Address already in use")
+                    is_caroot_cert_failure=$(echo $stunnel_status | grep "certificate verify failed")
+                    if [ -n "$is_binding_error" ]; then
+                        eecho "[FATAL] Restarting stunnel failed.$used_port port is already being used by other process.!"
+                        eecho "It's recommended to unmount all shares from $l_host and then remount shares using aznfs mount helper!"
+                    elif [ -n "$is_caroot_cert_failure" ]; then
+                        # TODO: confirm exactly which CA root cert to download for production.
+                        eecho "[FATAL] Restarting stunnel failed. CA root certificate is either missing or is unable to authenticate TLS server certificate."
+                        eecho "Please download the CA root certificate from https://learn.microsoft.com/en-us/azure/security/fundamentals/azure-ca-details"
+                        eecho "It's recommended to unmount all shares from $l_host and then remount shares using aznfs mount helper!"
+                    else
+                        eecho "[FATAL] azfilenfs-watchdog service is unable to start stunnel process for '${l_conf}'!"
+                        eecho "Please check the stunnel logs in $l_log for more details."
+                        eecho "It's recommended to unmount all shares from $l_host and then remount shares using aznfs mount helper!"
+		    fi
+		fi
+	    else
+	        vecho "stunnel is running!!"
+	    fi
+        fi
+    done
+}
+
+
+vecho "Starting aznfswatchdog..."
+
+# Detect and log distro, bash and AZNFS-mount version
+log_version_info
+
+# Dump NAT table once on startup in case we have reported conflicts.
+vecho "NAT table:\n$(iptables-save -t nat)"
+conntrack -L > /dev/null
+
+# conntrack timewait timeout higher than the TCP timewait timeout value isn't very valuable.
+conntrack_timeo_timew=$(cat /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_time_wait 2>/dev/null)
+if [ $? -eq 0 ] && [ -n "$conntrack_timeo_timew" -a $conntrack_timeo_timew -gt $AZNFS_TIMEWAIT_TIMEOUT ]; then
+        vecho "Changing /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_time_wait [$conntrack_timeo_timew -> $AZNFS_TIMEWAIT_TIMEOUT]"
+        echo $AZNFS_TIMEWAIT_TIMEOUT > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_time_wait
+fi
+
+if ! chattr -f +i $MOUNTMAP; then
+    wecho "chattr does not work for ${MOUNTMAP}!"
+fi
+
+# For NFS V4 mount map file
+if [ ! -f $AZ_FILES_MOUNTMAP ]; then
+    touch $AZ_FILES_MOUNTMAP
+    if [ $? -ne 0 ]; then
+        eecho "[FATAL] Not able to create '${AZ_FILES_MOUNTMAP}'!"
+        exit 1
+    fi
+fi
+
+if ! chattr -f +i $AZ_FILES_MOUNTMAP; then
+    wecho "chattr does not work for ${AZ_FILES_MOUNTMAP}!"
+fi
+
+#
+# If we are not skipping IP change detection for regional accounts, then mountmap file will be updated every minute
+# due to the change in IP for regional account FQDN. If we use standard MOUNTMAP_INACTIVITY_SECS,
+# then this will prevent mountmap entry to be deleted. We set this to less than 1 minute in this case.
+#
+if [ "$AZNFS_SKIP_IP_CHANGE_DETECTION_FOR_REGIONAL_ACCOUNTS" == "0" ]; then
+    MOUNTMAP_INACTIVITY_SECS=45
+fi
+
+while :; do
+    sleep $MONITOR_INTERVAL_SECS
+    vecho "Processing NFSV3 mounts"
+    processNFS3Mounts
+    vecho "Processing NFSV4 mounts"
+    processNFS4Mounts
 done
+
