refactor mtime

diff --git a/src/aznfswatchdogv4 b/src/aznfswatchdogv4
--- a/src/aznfswatchdogv4
+++ b/src/aznfswatchdogv4
@@ -9,7 +9,11 @@
 # Watchdog for monitoring unmounts and stunnel processes
 #
 
-mtime_mountmap=0
+mtime_mountmapv4=0
+mtime_mountmapv4nontls=0
+# How often do we check for change in FQDN->IP?
+IP_CHANGE_DETECTION_FREQUENCY=60
+next_ip_change_detection_epoch=0
 
 #
 # Kill stunnel process and clean up stunnel files generated by aznfs mount helper
@@ -142,17 +146,17 @@ cleanup_mount()
     flock -e $fd2
 
     # Delete IFF mountmap is not changed since we read it above.
-    l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
+    l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmapv4")
 
     #
     # Update mountmap mtime in case of successful updation of MOUNTMAPv4,
     # so that we can distinguish between MOUNTMAPv4 mtime changing because
     # of our action or some mount helper changing it. In the former case
-    # it's safe to update the MOUNTMAPv4, so update mtime_mountmap to the
+    # it's safe to update the MOUNTMAPv4, so update mtime_mountmapv4 to the
     # mtime after this update.
     #
     if [ $? -eq 0 ]; then
-        mtime_mountmap=$l_mtime
+        mtime_mountmapv4=$l_mtime
     else
         # If the mountmap file is changed since we read it, we need to read it again - don't modify anything.
         eecho "Failed to delete entry from ${MOUNTMAPv4}! Entry: [$line]"
@@ -188,7 +192,7 @@ process_nfsv4_mounts()
     #
     exec {fd}<$MOUNTMAPv4
     flock -e $fd
-    mtime_mountmap=$(stat -c%Y $MOUNTMAPv4)
+    mtime_mountmapv4=$(stat -c%Y $MOUNTMAPv4)
     IFS=$'\n' lines=$(cat $MOUNTMAPv4)
     flock -u $fd
     exec {fd}<&-
@@ -235,7 +239,7 @@ process_nfsv4_mounts()
             exec {fd2}<$MOUNTMAPv4
             flock -e $fd2
             l_mtime=$(ensure_mountmapv4_not_exist "$line")
-            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            [ $? -eq 0 ] && mtime_mountmapv4=$l_mtime
             flock -u $fd2
             exec {fd2}<&-
             continue
@@ -268,17 +272,10 @@ process_nfsv4_mounts()
             cleanup_mount $l_conf $l_log $l_pid $line
             continue
         else
-        #daniewo section
-            # vecho "Mounted shares found for host $l_ip with accept port $accept_port."
-            #Daniewo updates for ip change detection
-            #Do a check for cadence, don't do every iteration.
-            #then, check here, we should check the FQDN -> IP from the above, l_host is the accountname, and then
-            #grep against the l_conf for the IP
-            #if IP is updated, then reconfigure stunnel and probably go to last step and skip this. or move this check
-            # above
-           
-            #now we have the line with the accept port, take that same line but grab the mountpoint
-            #mountpoint = 
+            #
+            # Fetch FSLocationIP from the virtual file and check if it's updated for migration scenario. 
+            # The virtual file is at the mountpoint and named with the crc32 value in the mountmap entry.
+            #
             local mountpoint=$(echo "$findmnt_output" | awk '{print $1}' | sed 's/^[└├│─]*//g')
             vecho "daniewo mountpoint = $mountpoint"
             l_fslocation_line=$(cat "${mountpoint}/${l_crc_32}")
@@ -292,27 +289,22 @@ process_nfsv4_mounts()
                 return 1
             fi
 
-            vecho "daniewo l_fslocationIP = $l_fslocationIP, l_prt = $l_prt"
-            #compare the ip from fslocationip and mountmap ip l_ip
+            #
+            # If FSLocationIP is not empty, and updated from the IP stored in MountMap and PRT is in migration stage, update.
+            # Mountmap, config, log, and checksumhash need to be updtaed accordingly. Then restart stunnel with new config file.
+            #
+            if [ -n "$l_fslocationIP" -a "$l_fslocationIP" != "$l_ip" -a "$l_prt" -ne 0 ]; then 
+                vecho " IP for $l_host changed [$l_ip -> $l_fslocationIP]."
 
-            #fake just for this once to see how it will handle killing and starting a new stunnel
-            # l_prt=5
-            # l_fslocationIP="20.150.93.156" #fake new ip for testing
-
-            if [ -n "$l_fslocationIP" -a "$l_fslocationIP" != "$l_ip" -a "$l_prt" -ne 0 ]; then #Migration stage >= 5
-                vecho "daniewo IP for $l_host changed [$l_ip -> $l_fslocationIP]."
-
-                #reminder to check checksum in the l_checksumhash  variable and update so that mountmap is updated.
-                #mountmap needs to update the l_conf, l_log, l_ip and checksumhash
                 new_ip=$l_fslocationIP
                 IP_changed=true
 
-                #sed command old ip with new ip in l_conf file. then mv after.
+                #Update stunnel config file with new IP
                 out=$(sed "s/${l_ip}/${new_ip}/g" $l_conf)
 
                 ret=$?
 
-                #kill old stunnel process and remove old files
+                #kill old stunnel process and remove old files 
                 cleanup_stunnel_files $l_conf $l_log $l_pid
 
                 #update the contents of the l_conf file with the new ip
@@ -338,7 +330,7 @@ process_nfsv4_mounts()
                 chattr -f +i $new_conf_file_path
 
                 #update mountmapentry to update checksumhash and ip files
-                newchecksumhash=`cksum $new_conf_file_path | awk '{print $1}'` #make sure nothing else is being updated after this
+                newchecksumhash=`cksum $new_conf_file_path | awk '{print $1}'`
                 chattr -f -i $MOUNTMAPv4
                 outmountmap=$(sed -e "s/$l_checksumhash/$newchecksumhash/g" -e "s/$l_ip/$new_ip/g" $MOUNTMAPv4)
 
@@ -348,7 +340,6 @@ process_nfsv4_mounts()
                     #
                     # If this echo fails then MOUNTMAPv4 could be truncated.
                     #
-                    eecho "daniewo content of $outmountmap"
                     echo "$outmountmap" > $MOUNTMAPv4
                     ret=$?
                     out=
@@ -379,7 +370,8 @@ process_nfsv4_mounts()
                 eecho "Failed to get the checksum hash of file: '${l_conf}'!"
             fi
 
-            if [ $checksumHash != $l_checksumhash ] && [ "$IP_changed" = "false" ]; then #daniewo skip if migrated
+            # If files were updated outside of IP being changed, then cleanup the mount.
+            if [ $checksumHash != $l_checksumhash ] && [ "$IP_changed" = "false" ]; then
                 eecho "'${l_conf}' file has modified!"
                 eecho "It's not recommended to modify '${l_conf}' file created by aznfs mount helper!"
                 eecho "watchdog service will do cleanup, kill stunnel process with pid:$(cat $l_pid) and remove '${l_conf}'; '${l_log}'; '${l_pid}'!"
@@ -421,8 +413,6 @@ process_nfsv4_mounts()
 process_nfsv4_nontlsmounts()
 {
     epoch_now=$(date +%s)
-    vecho "Process nfsv4 non tls mounts"
-    eecho "Daniewo process non tls mounts now"
     #
     # Go over all lines in MOUNTMAPv4NONTLS and check them for two things:
     # 1. Is that entry still in use by at least one aznfs mount, if not remove the entry.
@@ -440,28 +430,19 @@ process_nfsv4_nontlsmounts()
     # in the next iteration when it's safer.
     #
     exec {fd}<$MOUNTMAPv4NONTLS
-    #lock? 
     flock -e $fd
-    mtime_mountmap=$(stat -c%Y $MOUNTMAPv4NONTLS)
+    mtime_mountmapv4nontls=$(stat -c%Y $MOUNTMAPv4NONTLS)
     IFS=$'\n' lines=$(cat $MOUNTMAPv4NONTLS)
     flock -u $fd
     exec {fd}<&-
 
-    #can tune this, but hardcode to true for now. 
-    # vecho "now: $epoch_now"
-    # vecho "next: $next_ip_change_detection_epoch"
-    do_ip_change_detection=true
-    #DANIEWO LOCK THE MOUNTMAPFILEV4 IN CASE A MOUNT IS HAPPENING AT THE SAME TIME, DO NOT PROCESS DURING THEN.
+    #Can get rid of the below if every 30 seconds is fine.
+    do_ip_change_detection=false
     
-    # if [ $epoch_now -ge $next_ip_change_detection_epoch ]; then
-    #     do_ip_change_detection=true
-    #         next_ip_change_detection_epoch=$(expr $(date +%s) + $IP_CHANGE_DETECTION_FREQUENCY)
-    # fi
-
-    #do we need to findmnt? copy from nfsv4 or nfsv3 watchdog.
-    
-
-    #the bulk of this logic could be shared between v3 and v4 but would need to parameterize the file names
+    if [ $epoch_now -ge $next_ip_change_detection_epoch ]; then
+        do_ip_change_detection=true
+            next_ip_change_detection_epoch=$(expr $(date +%s) + $IP_CHANGE_DETECTION_FREQUENCY)
+    fi
 
     for line in $lines; do
         if [ -z "$line" ]; then
@@ -469,7 +450,7 @@ process_nfsv4_nontlsmounts()
         fi
         #
         # MOUNTMAPv4nontls line is of the form:
-        # account.blob.preprod.core.windows.net <local ip> <public ip> [<PID>] <crc32>
+        # account.file.core.windows.net <local ip> <public ip> [<PID>] <crc32>
         # compare publicIP and crc32
         #
 
@@ -485,13 +466,11 @@ process_nfsv4_nontlsmounts()
 
         eecho "l_host: $l_host l_crc32: $l_crc32 l_ip: $l_ip l_nfsip: $l_nfsip mountpoint: $mountpoint"
 
-        
-
         # Since we added it to the MOUNTMAPv4 file, it cannot be invalid.
         if ! is_private_ip "$l_ip"; then
             wecho "[FATAL] local ip ($l_ip) is invalid!"
             l_mtime=$(ensure_mountmap_not_exist "$line" "$MOUNTMAPv4NONTLS")
-            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            [ $? -eq 0 ] && mtime_mountmapv4nontls=$l_mtime
             continue
         fi
 
@@ -499,19 +478,16 @@ process_nfsv4_nontlsmounts()
         if ! is_valid_ipv4_address "$l_nfsip"; then
             wecho "[FATAL] File endpoint ip ($l_nfsip) is invalid!"
             l_mtime=$(ensure_mountmap_not_exist "$line" "$MOUNTMAPv4NONTLS")
-            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            [ $? -eq 0 ] && mtime_mountmapv4nontls=$l_mtime
             continue
         fi
 
         #
-        # Delete entry from MOUNTMAPv3 if there are no mounted shares on that host.
-        # As long as we have at least one mount using the MOUNTMAPv3 entry, we leave
-        # it around.
+        # Delete entry from MOUNTMAPv4NONTLS if there are no mounted shares on that host.
+        # As long as we have at least one mount using the MOUNTMAPv4NONTLS entry, we leave
+        # it around. Can just search for account name as we don't support multi-mount migration scenarios on AZNFS for now.
         #
-        eecho "daniewo accountname = $accname"
         findmnt=$(findmnt -m | grep "${accname}") #>/dev/null)# bugged as it gives the output to dev/null
-        eecho "daniewo findmnt: $accname"
-        eecho "findmnt output: $findmnt"
         do_unmount_gc_nfsv4=true
         #if ! echo "$findmnt" >/dev/null; then
         if [ -z "$findmnt" ] ; then
@@ -519,22 +495,22 @@ process_nfsv4_nontlsmounts()
                 eecho "No mounted shares for host $l_host, deleting from ${MOUNTMAPv4NONTLS} [$line]." #update to correct file name
 
                 # Delete IFF mountmap is not changed since we read it above.
-                l_mtime=$(ensure_mountmap_not_exist "$line" "$MOUNTMAPv4NONTLS") #"$mtime_mountmap")
+                l_mtime=$(ensure_mountmap_not_exist "$line" "$MOUNTMAPv4NONTLS") #"$mtime_mountmapv4nontls")
 
                 #
                 # Update ifmatch time in case of successful updation of MOUNTMAPv4NONTLS,
-                # so that we can distinguish between MOUNTMAPv3 mtime changing because
+                # so that we can distinguish between MOUNTMAPv4NONTLS mtime changing because
                 # of our action or some mount helper changing it. In the former case
-                # it's safe to update the MOUNTMAPv3, so update mtime_mountmap to the
+                # it's safe to update the MOUNTMAPv4NONTLS, so update mtime_mountmapv4nontls to the
                 # mtime after this update.
                 #
-                [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+                [ $? -eq 0 ] && mtime_mountmapv4nontls=$l_mtime
                 continue
             fi
         else
             #
             # Verify that iptable entry should be present for corresponding
-            # MOUNTMAPv3 entry if the share is not unmounted.
+            # MOUNTMAPv4NONTLS entry if the share is not unmounted.
             #
             # Note: This is extra protection in case user flushes the iptable
             #       entries or removes it by mistake. This should not be
@@ -548,8 +524,6 @@ process_nfsv4_nontlsmounts()
             #
             reconcile_conntrack "$l_ip" "$l_nfsip"
             verify_iptable_entry "$l_ip" "$l_nfsip"
-            eecho "Daniewo, we are at reconcile and verify IP table, sunny path"
-
         fi
 
         #read into the line here to do the ip change detection. this is per Line.
@@ -564,38 +538,31 @@ process_nfsv4_nontlsmounts()
             return 1
         fi
 
+        # Ingest l_prt and l_fslocationIP from fslocation line. The format of the line is <migration stage>;<fslocationIP>
         IFS=";" read l_prt l_fslocationIP <<< "$l_fslocation_line"
-        # Release lock
-        #flock -u $fd4
-        #exec {fd4}<&-
-        # Daniewo look at the IP line in AZNFS.txt12345 for the file using l_crc32
+
+        # should we umount or do something else like log since the server may not be at that build yet?
         if [ -z "$l_host" -o -z "$l_ip" -o -z "$l_nfsip" -o -z "$l_crc32" ]; then
             wecho "[FATAL] Deleting invalid line in $MOUNTMAPv4NONTLS: [$line]!"
-            l_mtime=$(ensure_mountmap_not_exist "$line" "$MOUNTMAPv4NONTLS") #don't worry if it moves because we need to delete anyway
-            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            l_mtime=$(ensure_mountmap_not_exist "$line" "$MOUNTMAPv4NONTLS") 
+            [ $? -eq 0 ] && mtime_mountmapv4nontls=$l_mtime
             continue
         fi
+
         #
-        # We do IP change detection less frequently than unmount detection
-        # since it will cause DNS calls on network.
-        # this will eventually call a read on our virtual file which will tell us the migration stage and IP
+        # We probably don't need this as we are not making any DNS calls but instead reading from fslocation
         #
         if ! $do_ip_change_detection; then
             continue
         fi
 
-
-        #Daniewo we can hide behind PRT change as protection to know if we need to do IP change. So, even if it returns a different IP, prt will remain 
-        # 0 until migration stage 5 is hit. Therefore, we don't need to resolve any DNS until then.
-
-
-        #if l_nfsip is not empty and l_prt != 0, then we check. Otherwise, don't check.
-        eecho "DAniewo updatmountmapv3entry line: $line l_host: $l_host l_ip: $l_ip l_fslocationIP: $l_fslocationIP l_crc32: $l_crc32"
-        if [ -n "$l_fslocationIP" -a "$l_fslocationIP" != "$l_nfsip" -a $l_prt != 0 ]; then #change prt to the correct variable, it's probably <5 or something
+        #
+        # Check if the PRT is in the migration stage and if the IP Reported from Virtual File is updated yet.
+        #
+        if [ -n "$l_fslocationIP" -a "$l_fslocationIP" != "$l_nfsip" -a $l_prt != 0 ]; then 
             eecho "IP for $l_host changed [$l_nfsip -> $l_fslocationIP]."
 
             # This will update DNAT rule as well.
-            eecho "DAniewo updatmountmapv3entry line: $line l_host: $l_host l_ip: $l_ip l_fslocationIP: $l_fslocationIP l_crc32: $l_crc32"
             if ! update_mountmap_entry "$line" "$l_host $l_ip $l_fslocationIP $l_crc32" "$MOUNTMAPv4NONTLS"; then
                 eecho "Will reattempt the operation in next iteration."
             else
@@ -626,10 +593,13 @@ if ! chattr -f +i $MOUNTMAPv4; then
     wecho "chattr does not work for ${MOUNTMAPv4}!"
 fi
 
+if ! chattr -f +i $MOUNTMAPv4NONTLS; then
+    wecho "chattr does not work for ${MOUNTMAPv4NONTLS}!"
+fi
+
 while :; do
     sleep $MONITOR_INTERVAL_SECS
     process_nfsv4_mounts
     process_nfsv4_nontlsmounts
-    #daniewo process nontlsmounts and track for migration
 
 done
