Init

diff --git a/src/aznfswatchdogv4 b/src/aznfswatchdogv4
--- a/src/aznfswatchdogv4
+++ b/src/aznfswatchdogv4
@@ -17,9 +17,12 @@ cleanup_stunnel_files()
     local l_conf=$1
     local l_log=$2
     local l_pid=$3
+    local accept_port
 
     # Kill stunnel process first.
     pid=$(cat $l_pid)
+    accept_port=$(cat $l_conf | grep accept | cut -d ':' -f 2)
+    pecho "killing stunnle process with pid: $pid on port: $accept_port"
     kill -9 $pid
     if [ $? -ne 0 ]; then
         eecho "[FATAL] Unable to kill stunnel process $pid!"
@@ -48,52 +51,48 @@ cleanup_stunnel_files()
 #
 ensure_mountmapv4_not_exist()
 {
-    (
-        flock -e 999
-
-        #
-        # If watchdog wants to delete the entry only if MOUNTMAPv4 has not changed since
-        # watchdog looked up, honour that.
-        #
-        local ifmatch="$2"
-        if [ -n "$ifmatch" ]; then
-            local mtime=$(stat -c%Y $MOUNTMAPv4)
-            if [ "$mtime" != "$ifmatch" ]; then
-                eecho "[$1] Refusing to remove from ${MOUNTMAPv4} as $mtime != $ifmatch!"
-                return 1
-            fi
-        fi
-
-        chattr -f -i $MOUNTMAPv4
-        #
-        # We overwrite the file instead of inplace update by sed as that has a
-        # very bad side-effect of creating a new MOUNTMAPv4 file. This breaks
-        # any locking that we dependent on the old file.
-        #
-        out=$(sed "\%^${1}$%d" $MOUNTMAPv4)
-        ret=$?
-        if [ $ret -eq 0 ]; then
-            #
-            # If this echo fails then MOUNTMAPv4 could be truncated.
-            #
-            echo "$out" > $MOUNTMAPv4
-            ret=$?
-            out=
-            if [ $ret -ne 0 ]; then
-                eecho "*** [FATAL] MOUNTMAPv4 may be in inconsistent state, contact Microsoft support ***"
-            fi
-        fi
-
-        if [ $ret -ne 0 ]; then
-            chattr -f +i $MOUNTMAPv4
-            eecho "[$1] failed to remove from ${MOUNTMAPv4}!"
+    #
+    # If watchdog wants to delete the entry only if MOUNTMAPv4 has not changed since
+    # watchdog looked up, honour that.
+    #
+    local ifmatch="$2"
+    if [ -n "$ifmatch" ]; then
+        local mtime=$(stat -c%Y $MOUNTMAPv4)
+        if [ "$mtime" != "$ifmatch" ]; then
+            eecho "[$1] Refusing to remove from ${MOUNTMAPv4} as $mtime != $ifmatch!"
             return 1
         fi
-        chattr -f +i $MOUNTMAPv4
+    fi
 
-        # Return the mtime after our mods.
-        echo $(stat -c%Y $MOUNTMAPv4)
-    ) 999<$MOUNTMAPv4
+    chattr -f -i $MOUNTMAPv4
+    #
+    # We overwrite the file instead of inplace update by sed as that has a
+    # very bad side-effect of creating a new MOUNTMAPv4 file. This breaks
+    # any locking that we dependent on the old file.
+    #
+    out=$(sed "\%^${1}$%d" $MOUNTMAPv4)
+    ret=$?
+    if [ $ret -eq 0 ]; then
+        #
+        # If this echo fails then MOUNTMAPv4 could be truncated.
+        #
+        echo "$out" > $MOUNTMAPv4
+        ret=$?
+        out=
+        if [ $ret -ne 0 ]; then
+            eecho "*** [FATAL] MOUNTMAPv4 may be in inconsistent state, contact Microsoft support ***"
+        fi
+    fi
+
+    if [ $ret -ne 0 ]; then
+        chattr -f +i $MOUNTMAPv4
+        eecho "[$1] failed to remove from ${MOUNTMAPv4}!"
+        return 1
+    fi
+    chattr -f +i $MOUNTMAPv4
+
+    # Return the mtime after our mods.
+    echo $(stat -c%Y $MOUNTMAPv4)
 }
 
 process_nfsv4_mounts()
@@ -142,6 +141,11 @@ process_nfsv4_mounts()
         exit 1
     fi
 
+    if [ -z "$NETSTATCOMMAND" ]; then
+        eecho "[FATAL] No socket statistics command (netstat or ss) found! Aznfswatchdogv4 service is exiting. Please contact Microsoft support"
+        exit 1
+    fi
+
     for line in $lines; do
         if [ -z "$line" ]; then
             continue
@@ -149,19 +153,29 @@ process_nfsv4_mounts()
 
         #
         # MOUNTMAPv4 line is of the form:
-        # account.file.preprod.core.windows.net;<stunnel_account.file.preprod.core.windows.net.conf path>;<stunnel_account.file.preprod.core.windows.net.log path>;<stunnel_account.file.preprod.core.windows.net.pid path>;<checksumHash>
+        # account.file.preprod.core.windows.net;<stunnel_account.file.preprod.core.windows.net.conf path>;<stunnel_account.file.preprod.core.windows.net.log path>;<stunnel_account.file.preprod.core.windows.net.pid path>;<checksumHash>;<status>
         #
-        IFS=";" read l_host l_conf l_log l_pid l_checksumhash <<< "$line"
+        IFS=";" read l_host l_conf l_log l_pid l_checksumhash l_status <<< "$line"
 
         if [ -z "$l_host" -o -z "$l_conf" -o -z "$l_pid" ]; then
             wecho "[FATAL] Deleting invalid line in $MOUNTMAPv4: [$line]!"
+            exec {fd2}<$MOUNTMAPv4
+            flock -e $fd2
             l_mtime=$(ensure_mountmapv4_not_exist "$line")
             [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            flock -u $fd2
+            exec {fd2}<&-
+            continue
+        fi
+
+        # Skip if the status is waiting, which means the mountscript is still processing the mount.
+        if [ "$l_status" == "waiting" ]; then
+            # vecho "Skipping entry with status 'waiting': [$line]"
             continue
         fi
 
         accept_port=$(cat $l_conf | grep accept | cut -d ':' -f 2)
-        vecho "accept_port: $accept_port"
+        # vecho "accept_port: $accept_port"
 
         #
         # Delete entry from MOUNTMAPv4 if there are no mounted shares on that host.
@@ -169,9 +183,17 @@ process_nfsv4_mounts()
         # it around.
         #
         if ! echo "$findmnt" | grep "$accept_port" >/dev/null; then
-            pecho "No mounted shares for host $l_host, deleting from ${MOUNTMAPv4} [$line]."
+            pecho "No mounted shares for host $l_host with accept port $accept_port, deleting from ${MOUNTMAPv4} [$line]."
 
-            cleanup_stunnel_files $l_conf $l_log $l_pid
+            # Need to lock MOUNTMAPv4 and config file since the mountscript could be updating them.
+            exec {fd1}<$l_conf
+            flock -e $fd1
+            exec {fd2}<$MOUNTMAPv4
+            flock -e $fd2
+
+            # ensure_mountmapv4_not_exist() fails if mountmap is changed since we read it above.
+            # Therefore, we need to update mountmap first and then delete stunnle files as the mountmap file might have changed.
+            # Otherwise, we might end up removing stunnle files without removing the entry from mountmap, which might cause duplicate entries in mountmap.
 
             # Delete IFF mountmap is not changed since we read it above.
             l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
@@ -183,9 +205,28 @@ process_nfsv4_mounts()
             # it's safe to update the MOUNTMAPv4, so update mtime_mountmap to the
             # mtime after this update.
             #
-            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            if [ $? -eq 0 ]; then
+                mtime_mountmap=$l_mtime
+            else
+                # If the mountmap file is changed since we read it, we need to read it again - don't modify anything.
+                eecho "Failed to delete entry from ${MOUNTMAPv4}! Entry: [$line]"
+                flock -u $fd2
+                exec {fd2}<&-
+                flock -u $fd1
+                exec {fd1}<&-
+                continue
+            fi
+
+            cleanup_stunnel_files $l_conf $l_log $l_pid
+
+            flock -u $fd2
+            exec {fd2}<&-
+            flock -u $fd1
+            exec {fd1}<&-
             continue
         else
+            # vecho "Mounted shares found for host $l_host with accept port $accept_port."
+
             # Check if checksumHash for stunnel.conf file has changed.
             # Customers should not modify stunnel.conf files created by aznfs mount helper.
             checksumHash=`cksum $l_conf | awk '{print $1}'`
@@ -199,15 +240,44 @@ process_nfsv4_mounts()
                 eecho "watchdog service will do cleanup, kill stunnel process with pid:$(cat $l_pid) and remove '${l_conf}'; '${l_log}'; '${l_pid}'!"
                 eecho "Please remount the shares from ${l_host} using aznfs mount helper."
 
-                cleanup_stunnel_files $l_conf $l_log $l_pid
+                # Need to lock MOUNTMAPv4 and config file since the mountscript could be updating them.
+                exec {fd1}<$l_conf
+                flock -e $fd1
+                exec {fd2}<$MOUNTMAPv4
+                flock -e $fd2
 
                 # Delete IFF mountmap is not changed since we read it above.
                 l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
-                [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+
+                #
+                # Update ifmatch time in case of successful updation of MOUNTMAPv4,
+                # so that we can distinguish between MOUNTMAPv4 mtime changing because
+                # of our action or some mount helper changing it. In the former case
+                # it's safe to update the MOUNTMAPv4, so update mtime_mountmap to the
+                # mtime after this update.
+                #
+                if [ $? -eq 0 ]; then
+                    mtime_mountmap=$l_mtime
+                else
+                    # If the mountmap file is changed since we read it, we need to read it again - don't modify anything.
+                    eecho "Failed to delete entry from ${MOUNTMAPv4}! Entry: [$line]"
+                    flock -u $fd2
+                    exec {fd2}<&-
+                    flock -u $fd1
+                    exec {fd1}<&-
+                    continue
+                fi
+
+                cleanup_stunnel_files $l_conf $l_log $l_pid
+
+                flock -u $fd2
+                exec {fd2}<&-
+                flock -u $fd1
+                exec {fd1}<&-
                 continue
             fi
 
-            is_stunnel_running=$(netstat -anp | grep stunnel | grep `cat $l_pid`)
+            is_stunnel_running=$($NETSTATCOMMAND -anp | grep stunnel | grep `cat $l_pid`)
             if [ -z "$is_stunnel_running" ]; then
                 vecho "stunnel is not running! Restarting the stunnel"
 
@@ -229,8 +299,6 @@ process_nfsv4_mounts()
                         eecho "It's recommended to unmount all shares from $l_host and then remount shares using aznfs mount helper!"
                     fi
                 fi
-            else
-                vecho "stunnel is running!!"
             fi
         fi
     done
