Revert watchdog changes

diff --git a/src/aznfswatchdogv4 b/src/aznfswatchdogv4
--- a/src/aznfswatchdogv4
+++ b/src/aznfswatchdogv4
@@ -9,7 +9,7 @@
 # Watchdog for monitoring unmounts and stunnel processes
 #
 
-mtime_mountmap=0
+# mtime_mountmap=0
 
 #
 # Kill stunnel process and clean up stunnel files generated by aznfs mount helper
@@ -97,43 +97,49 @@ ensure_mountmapv4_not_exist()
     echo $(stat -c%Y $MOUNTMAPv4)
 }
 
-cleanup_mount()
-{
-    local l_conf=$1
-    local l_log=$2
-    local l_pid=$3
-    local line=$4
+# cleanup_mount()
+# {
+#     local l_conf=$1
+#     local l_log=$2
+#     local l_pid=$3
+#     local line=$4
 
-    # Need to lock MOUNTMAPv4 since the mountscript could modify them as well.
-    exec {fd2}<$MOUNTMAPv4
-    flock -e $fd2
+#     # Need to lock MOUNTMAPv4 and config file since the mountscript could be updating them.
+#     exec {fd1}<$l_conf
+#     flock -e $fd1
+#     exec {fd2}<$MOUNTMAPv4
+#     flock -e $fd2
 
-    # Delete IFF mountmap is not changed since we read it above.
-    l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
+#     # Delete IFF mountmap is not changed since we read it above.
+#     l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
 
-    #
-    # Update mountmap mtime in case of successful updation of MOUNTMAPv4,
-    # so that we can distinguish between MOUNTMAPv4 mtime changing because
-    # of our action or some mount helper changing it. In the former case
-    # it's safe to update the MOUNTMAPv4, so update mtime_mountmap to the
-    # mtime after this update.
-    #
-    if [ $? -eq 0 ]; then
-        mtime_mountmap=$l_mtime
-    else
-        # If the mountmap file is changed since we read it, we need to read it again - don't modify anything.
-        eecho "Failed to delete entry from ${MOUNTMAPv4}! Entry: [$line]"
-        flock -u $fd2
-        exec {fd2}<&-
-        return 1
-    fi
+#     #
+#     # Update mountmap mtime in case of successful updation of MOUNTMAPv4,
+#     # so that we can distinguish between MOUNTMAPv4 mtime changing because
+#     # of our action or some mount helper changing it. In the former case
+#     # it's safe to update the MOUNTMAPv4, so update mtime_mountmap to the
+#     # mtime after this update.
+#     #
+#     if [ $? -eq 0 ]; then
+#         mtime_mountmap=$l_mtime
+#     else
+#         # If the mountmap file is changed since we read it, we need to read it again - don't modify anything.
+#         eecho "Failed to delete entry from ${MOUNTMAPv4}! Entry: [$line]"
+#         flock -u $fd2
+#         exec {fd2}<&-
+#         flock -u $fd1
+#         exec {fd1}<&-
+#         return 1
+#     fi
 
-    cleanup_stunnel_files $l_conf $l_log $l_pid
+#     cleanup_stunnel_files $l_conf $l_log $l_pid
 
-    flock -u $fd2
-    exec {fd2}<&-
-    return 0
-}
+#     flock -u $fd2
+#     exec {fd2}<&-
+#     flock -u $fd1
+#     exec {fd1}<&-
+#     return 0
+# }
 
 process_nfsv4_mounts()
 {
@@ -229,7 +235,34 @@ process_nfsv4_mounts()
         if ! echo "$findmnt" | grep "$accept_port" >/dev/null; then
             pecho "No mounted shares for host $l_ip with accept port $accept_port, deleting from ${MOUNTMAPv4} [$line]."
 
-            cleanup_mount $l_conf $l_log $l_pid $line
+            # cleanup_mount $l_conf $l_log $l_pid $line
+            # Need to lock MOUNTMAPv4 and config file since the mountscript could be updating them.
+            exec {fd2}<$MOUNTMAPv4
+            flock -e $fd2
+            # ensure_mountmapv4_not_exist() fails if mountmap is changed since we read it above.
+            # Therefore, we need to update mountmap first and then delete stunnle files as the mountmap file might have changed.
+            # Otherwise, we might end up removing stunnle files without removing the entry from mountmap, which might cause duplicate entries in mountmap.
+            # Delete IFF mountmap is not changed since we read it above.
+            l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
+            #
+            # Update ifmatch time in case of successful updation of MOUNTMAPv4,
+            # so that we can distinguish between MOUNTMAPv4 mtime changing because
+            # of our action or some mount helper changing it. In the former case
+            # it's safe to update the MOUNTMAPv4, so update mtime_mountmap to the
+            # mtime after this update.
+            #
+            if [ $? -eq 0 ]; then
+                mtime_mountmap=$l_mtime
+            else
+                # If the mountmap file is changed since we read it, we need to read it again - don't modify anything.
+                eecho "Failed to delete entry from ${MOUNTMAPv4}! Entry: [$line]"
+                flock -u $fd2
+                exec {fd2}<&-
+                continue
+            fi
+            cleanup_stunnel_files $l_conf $l_log $l_pid
+            flock -u $fd2
+            exec {fd2}<&-
             continue
         else
             # vecho "Mounted shares found for host $l_ip with accept port $accept_port."
@@ -247,7 +280,32 @@ process_nfsv4_mounts()
                 eecho "watchdog service will do cleanup, kill stunnel process with pid:$(cat $l_pid) and remove '${l_conf}'; '${l_log}'; '${l_pid}'!"
                 eecho "Please remount the shares from ${l_ip} using aznfs mount helper."
 
-                cleanup_mount $l_conf $l_log $l_pid $line
+                # cleanup_mount $l_conf $l_log $l_pid $line
+
+                # Need to lock MOUNTMAPv4 and config file since the mountscript could be updating them.
+                exec {fd2}<$MOUNTMAPv4
+                flock -e $fd2
+                # Delete IFF mountmap is not changed since we read it above.
+                l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
+                #
+                # Update ifmatch time in case of successful updation of MOUNTMAPv4,
+                # so that we can distinguish between MOUNTMAPv4 mtime changing because
+                # of our action or some mount helper changing it. In the former case
+                # it's safe to update the MOUNTMAPv4, so update mtime_mountmap to the
+                # mtime after this update.
+                #
+                if [ $? -eq 0 ]; then
+                    mtime_mountmap=$l_mtime
+                else
+                    # If the mountmap file is changed since we read it, we need to read it again - don't modify anything.
+                    eecho "Failed to delete entry from ${MOUNTMAPv4}! Entry: [$line]"
+                    flock -u $fd2
+                    exec {fd2}<&-
+                    continue
+                fi
+                cleanup_stunnel_files $l_conf $l_log $l_pid
+                flock -u $fd2
+                exec {fd2}<&-
                 continue
             fi
 
