initial commit with only refactoring of fname
quick push

refactor

add common methods to common.sh and add dns resolver for v4 mounts

add log

add common functions

switch to mounting with local ip for nfsv4 non tls

add fslocation file

add process nontls mount

add logging for watchdog

disable ipcheck

comment out looped for nontlsprocess

uncomment

comment first process so only one process is running

remove process nontls mounts for now as it's causing crash

enable nontls mount watchdog

add correct findmnt

fix findmnt

update watchdog with grep

update to 30 seconds and turn on ip detection

update watchdog

update watchdog

hardcode detection true

add vecho

add local_host echo

change to eecho

log fslocation entry

wrap in paren

update ipchange detection

remove the extra ping_newendpoint and see if it can just update the ip in iptable and keep localip the same

added logs

quick fix

add new scenarios for watchdog

add IP change detection for EIT

quick sync  failed since 2

add placeholder

diff --git a/src/aznfswatchdogv4 b/src/aznfswatchdogv4
--- a/src/aznfswatchdogv4
+++ b/src/aznfswatchdogv4
@@ -167,7 +167,9 @@ process_nfsv4_mounts()
     # MOUNTMAPv4 entry whose all nfs file shares are unmounted, we know
     # for sure that it's not in use by any mount and can be removed.
     #
-    findmnt=$(findmnt | grep 'nfs4\|$LOCALHOST' 2>&1)
+    #findmnt=$(findmnt | grep 'nfs4\|$LOCALHOST' 2>&1)
+    findmnt=$(findmnt --raw --noheading -o MAJ:MIN,FSTYPE,SOURCE,TARGET,OPTIONS -t nfs 2>&1)
+    #daniewo use this findmnt to check against the fslocation file for the IP
 
     #
     # For no matching mounts also, findmnt exits with a failure return, so check
@@ -196,6 +198,8 @@ process_nfsv4_mounts()
         # MOUNTMAPv4 line is of the form:
         # <IP>;<stunnel_account.file.preprod.core.windows.net.conf path>;<stunnel_account.file.preprod.core.windows.net.log path>;<stunnel_account.file.preprod.core.windows.net.pid path>;<checksumHash>;<status>;<timeout>
         #
+        #daniewo #stunnel_account here is the destination IP address for the account.
+
         IFS=";" read l_ip l_conf l_log l_pid l_checksumhash l_status l_timeout <<< "$line"
 
         if [ -z "$l_ip" -o -z "$l_conf" -o -z "$l_pid" ]; then
@@ -234,8 +238,38 @@ process_nfsv4_mounts()
             cleanup_mount $l_conf $l_log $l_pid $line
             continue
         else
+        #daniewo section
             # vecho "Mounted shares found for host $l_ip with accept port $accept_port."
+            #Daniewo updates for ip change detection
+            #Do a check for cadence, don't do every iteration.
+            #then, check here, we should check the FQDN -> IP from the above, l_host is the accountname, and then
+            #grep against the l_conf for the IP
+            #if IP is updated, then reconfigure stunnel and probably go to last step and skip this. or move this check
+            # above
 
+            #daniewo get dest ip from mountmap file
+            ip_address=$(echo $l_conf | awk -F'.file' '{print $1}')
+            echo "The extracted IP address is: $ip_address"
+
+            #get matching ip address from fs location entry for the account name FQDN
+            local fslocation_entry=$(grep -m1 $l_host $VIRTUALFSLOCATION)
+            #probably need to check if it returns empty as well.
+
+            eecho "daniewo fslocation_entry = $fslocation_entry"
+
+            #extract fslocation entry
+            IFS=" " read l_fqdn new_ip l_prt <<< $fslocation_entry
+            eecho "daniewo $l_fqdn, $new_ip, $l_prt"
+
+            # check fslocation ip against the old ip that was in mountmap file
+            if [ "$ip_address" != "$new_ip" ]; then
+            eecho "daniewwo IP for $l_host changed [$l_nfsip -> $new_ip]."
+            fi
+
+            # update_mountmapv3_entry version of TLS which will update the mountmapv4 entry and update stunnel
+
+        #end daniewo section 
+        
             # Check if checksumHash for stunnel.conf file has changed.
             # Customers should not modify stunnel.conf files created by aznfs mount helper.
             checksumHash=`cksum $l_conf | awk '{print $1}'`
@@ -280,6 +314,225 @@ process_nfsv4_mounts()
     done
 }
 
+process_nfsv4_nontlsmounts()
+{
+    epoch_now=$(date +%s)
+    vecho "Process nfsv4 non tls mounts"
+    #
+    # Go over all lines in MOUNTMAPv4NONTLS and check them for two things:
+    # 1. Is that entry still in use by at least one aznfs mount, if not remove the entry.
+    # 2. Has the Blob endpoint address changed from what is stored?
+    #    If yes, update DNAT rule to point to the new address and update entry accordingly.
+    #
+    # Sample line in MOUNTMAPv4NONTLS.
+    # account.blob.preprod.core.windows.net 10.100.100.100 52.230.170.200
+    #
+    # where the format is
+    # blobendpoint_fqdn proxy_ip blobendpoint_ip
+    #
+    # We store the mtime of MOUNTMAPv4NONTLS while inside the lock so that if any mount helper process
+    # updates it after this we will skip modification for sake of safety. We will come to it
+    # in the next iteration when it's safer.
+    #
+    exec {fd}<$MOUNTMAPv4NONTLS
+    #lock? 
+    flock -e $fd
+    mtime_mountmap=$(stat -c%Y $MOUNTMAPv4NONTLS)
+    IFS=$'\n' lines=$(cat $MOUNTMAPv4NONTLS)
+    flock -u $fd
+    exec {fd}<&-
+
+    #can tune this, but hardcode to true for now. 
+    vecho "now: $epoch_now"
+    vecho "next: $next_ip_change_detection_epoch"
+    do_ip_change_detection=true
+    # if [ $epoch_now -ge $next_ip_change_detection_epoch ]; then
+    #     do_ip_change_detection=true
+    #         next_ip_change_detection_epoch=$(expr $(date +%s) + $IP_CHANGE_DETECTION_FREQUENCY)
+    # fi
+
+    #do we need to findmnt? copy from nfsv4 or nfsv3 watchdog.
+    findmnt=$(findmnt | grep 'nfs4' | grep -v "$LOCALHOST")
+
+    #the bulk of this logic could be shared between v3 and v4 but would need to parameterize the file names
+
+    for line in $lines; do
+        if [ -z "$line" ]; then
+            continue
+        fi
+        #
+        # MOUNTMAPv4nontls line is of the form:
+        # account.blob.preprod.core.windows.net <local ip> <public ip> [<PID>]
+        #
+        IFS=" " read l_host l_ip l_nfsip <<< "$line"
+
+        eecho "l_host: $l_host"
+
+        if [ -z "$l_host" -o -z "$l_ip" -o -z "$l_nfsip" ]; then
+            wecho "[FATAL] Deleting invalid line in $MOUNTMAPv4NONTLS: [$line]!"
+            l_mtime=$(ensure_mountmapv3_not_exist "$line")
+            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            continue
+        fi
+
+        # Since we added it to the MOUNTMAPv4 file, it cannot be invalid.
+        if ! is_private_ip "$l_ip"; then
+            wecho "[FATAL] local ip ($l_ip) is invalid!"
+            l_mtime=$(ensure_mountmapv3_not_exist "$line")
+            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            continue
+        fi
+
+        # Since we added it to the MOUNTMAPv3 file, it cannot be invalid.
+        if ! is_valid_ipv4_address "$l_nfsip"; then
+            wecho "[FATAL] Blob endpoint ip ($l_nfsip) is invalid!"
+            l_mtime=$(ensure_mountmapv3_not_exist "$line")
+            [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+            continue
+        fi
+
+        #
+        # Delete entry from MOUNTMAPv3 if there are no mounted shares on that host.
+        # As long as we have at least one mount using the MOUNTMAPv3 entry, we leave
+        # it around.
+        #
+        if ! echo "$findmnt" | grep "${l_ip}:" >/dev/null; then
+            if $do_unmount_gc; then
+                pecho "No mounted shares for host $l_host, deleting from ${MOUNTMAPv3} [$line]."
+
+                # Delete IFF mountmap is not changed since we read it above.
+                l_mtime=$(ensure_mountmapv3_not_exist "$line" "$mtime_mountmap")
+
+                #
+                # Update ifmatch time in case of successful updation of MOUNTMAPv3,
+                # so that we can distinguish between MOUNTMAPv3 mtime changing because
+                # of our action or some mount helper changing it. In the former case
+                # it's safe to update the MOUNTMAPv3, so update mtime_mountmap to the
+                # mtime after this update.
+                #
+                [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+                continue
+            fi
+        else
+            #
+            # Verify that iptable entry should be present for corresponding
+            # MOUNTMAPv3 entry if the share is not unmounted.
+            #
+            # Note: This is extra protection in case user flushes the iptable
+            #       entries or removes it by mistake. This should not be
+            #       required normally.
+            #
+            # We also reconcile conntrack entries stuck in some bad states which
+            # may hamper communication, f.e., in older kernels there's a bug due to
+            # which conntrack entry may get stuck in SYN_SENT state if client
+            # reuse the source port and keep retransmitting SYNs before the entry
+            # can timeout.
+            #
+            reconcile_conntrack "$l_ip" "$l_nfsip"
+            verify_iptable_entry "$l_ip" "$l_nfsip"
+            eecho "Daniewo, we are at reconcile and verify IP table, sunny path"
+
+        fi
+
+        #
+        # We do IP change detection less frequently than unmount detection
+        # since it will cause DNS calls on network.
+        # this will eventually call a read on our virtual file which will tell us the migration stage and IP
+        #
+        if ! $do_ip_change_detection; then
+            continue
+        fi
+
+        eecho "Daniewo, now to ip change detection"
+
+        #
+        # See if the account is regional account and we need to skip IP change detection for that.
+        #
+        # if should_skip_regional_account "$l_host"; then
+        #     continue
+        # fi
+
+        #
+        # Check if blob endpoint IP address changed.
+        # This is the migration check.
+        # Daniewo (within this migration check here, we can force an update to the previous IP in the file so that it shows as a different IP now
+        # and forces the IP to be different. )
+        #
+        #new_ip=$(resolve_ipv4 "$l_host" "false")
+        # this new_ip will be read from fslocation
+        #use a grep for the line. the format right now will be fqdn nfs_ip
+
+        eecho "daniewo local_host is $l_host"
+
+        fqdn_to_find=$l_host
+        # local fslocation_entry=$grep -m1 "^${fqdn} " $MOUNTMAPv3
+        
+        local fslocation_entry=$(grep -m1 $fqdn_to_find $VIRTUALFSLOCATION)
+
+        eecho "daniewo fslocation_entry = $fslocation_entry"
+        # FSLOCATION file will have format 
+        #lock FSLOCATION and find the line that has the matching FQDN == L_HOST
+        # FQDN DestinationIP PRT
+        # fqdn_to_find=$l_host
+        # nfs_ip=$(grep -m 1 "^$fqdn_to_find " $VIRTUALFSLOCATION | awk '{print $2}')
+
+        IFS=" " read l_fqdn new_ip l_prt <<< $fslocation_entry
+        eecho "daniewo $l_fqdn, $new_ip, $l_prt"
+
+        #daniewo check why this error code is not working
+
+        # # If we fail to resolve the host name, try next time.
+        # if [ $? -ne 0 ]; then
+        #     #
+        #     # If account is deleted then we need to delete the MOUNTMAPv3 entry along
+        #     # with the proxy iptable entry created for that account.
+        #     # Note that we don't delete if the MOUNTMAPv3 was changed recently since
+        #     # the account may have been re-created after the dns lookup failure.
+        #     #
+        #     if [ "$new_ip" == "NXDOMAIN" ]; then
+        #         pecho "Account corresponding to $l_host seems to have been deleted, deleting from ${MOUNTMAPv3} [$line]!"
+
+        #         l_mtime=$(ensure_mountmapv3_not_exist "$line" "$mtime_mountmap")
+        #         [ $? -eq 0 ] && mtime_mountmap=$l_mtime
+        #     else
+        #         eecho "resolve_ipv4($l_host) failed: $new_ip"
+        #     fi
+        #     continue
+        # fi
+
+        #then check IP detection change to see if it updates DNAT rules etc.
+
+        #
+        # If the IP changed for the Blob endpoint, we need to update the DNAT rule.
+        # This will take care of migration/failover causing the Blob endpoint IP to change.
+        #
+        if [ "$new_ip" != "$l_nfsip" ]; then
+            eecho "daniewwo IP for $l_host changed [$l_nfsip -> $new_ip]."
+
+            #if IP changed, still update the DNAT Rule but also see if this ends up being a ZRS tenant.
+            #Not sure what we will do for ZRS though, as we probably should not mount and only detect IP changes from fslocation
+            #but maybe FS location can return some sort of flag that says "hey we are ZRS FYI"
+            check_for_regional_account "$l_host"
+
+            #danniewo, watch out for this as if we are mounting a ZRS account,
+            # this can potentially be noisy.
+
+            # This will update DNAT rule as well.
+            if ! update_mountmapv3_entry "$line" "$l_host $l_ip $new_ip"; then
+                eecho "Will reattempt the operation in next iteration."
+            else
+                eecho "daniewo empty"
+                # mountpoint2048=$(echo "$findmnt" 2>/dev/null | egrep -m1 " nfs ${l_ip}:.*\<port=2048\>" | awk '{print $4}')
+                # mountpoint2048=$(echo -e "$mountpoint2048")
+                # if [ -n "$mountpoint2048" ]; then
+                #     ping_new_endpoint "$mountpoint2048" &
+                # fi
+            fi
+        fi
+    done
+
+}
+
 # Load common aznfs helpers.
 AZNFS_VERSION=4
 . /opt/microsoft/aznfs/common.sh
@@ -296,4 +549,7 @@ fi
 while :; do
     sleep $MONITOR_INTERVAL_SECS
     process_nfsv4_mounts
+    process_nfsv4_nontlsmounts
+    #daniewo process nontlsmounts and track for migration
+
 done
