Separate mountscripts and address comments

diff --git a/src/aznfswatchdog b/src/aznfswatchdog
--- a/src/aznfswatchdog
+++ b/src/aznfswatchdog
@@ -53,11 +53,8 @@ next_ip_change_detection_epoch=0
 #
 next_daily_run_epoch=$(expr $(date +%s) + 60)
 
-LOCALHOST="127.0.0.1"
-
 # Load common aznfs helpers.
 . /opt/microsoft/aznfs/common.sh
-
 
 # Create /opt/microsoft/aznfs/data/randbytes if not already created.
 if [ ! -s $RANDBYTES ]; then
@@ -368,64 +365,63 @@ log_version_info()
     vecho "AZNFS version: $current_version"
 }
 
-
 #
-# Delete entry from $AZ_FILES_MOUNTMAP.
+# Delete entry from MOUNTMAPv4.
 #
-ensure_az_files_mountmap_not_exist()
+ensure_mountmapv4_not_exist()
 {
     (
         flock -e 999
 
         #
-        # If watchdog wants to delete the entry only if AZ_FILES_MOUNTMAP has not changed since
+        # If watchdog wants to delete the entry only if MOUNTMAPv4 has not changed since
         # watchdog looked up, honour that.
         #
         local ifmatch="$2"
         if [ -n "$ifmatch" ]; then
-            local mtime=$(stat -c%Y $AZ_FILES_MOUNTMAP)
+            local mtime=$(stat -c%Y $MOUNTMAPv4)
             if [ "$mtime" != "$ifmatch" ]; then
-                eecho "[$1] Refusing to remove from ${AZ_FILES_MOUNTMAP} as $mtime != $ifmatch!"
+                eecho "[$1] Refusing to remove from ${MOUNTMAPv4} as $mtime != $ifmatch!"
                 return 1
             fi
         fi
 
-        chattr -f -i $AZ_FILES_MOUNTMAP
+        chattr -f -i $MOUNTMAPv4
         #
-        # We do this thing instead of inplace update by sed as that has a
-        # very bad side-effect of creating a new AZ_FILES_MOUNTMAP file. This breaks
+        # We overwrite the file instead of inplace update by sed as that has a
+        # very bad side-effect of creating a new MOUNTMAPv4 file. This breaks
         # any locking that we dependent on the old file.
         #
-        out=$(sed "\%^${1}$%d" $AZ_FILES_MOUNTMAP)
+        out=$(sed "\%^${1}$%d" $MOUNTMAPv4)
         ret=$?
         if [ $ret -eq 0 ]; then
             #
-            # If this echo fails then AZ_FILES_MOUNTMAP could be truncated.
+            # If this echo fails then MOUNTMAPv4 could be truncated.
             #
-            echo "$out" > $AZ_FILES_MOUNTMAP
+            echo "$out" > $MOUNTMAPv4
             ret=$?
             out=
             if [ $ret -ne 0 ]; then
-                eecho "*** [FATAL] AZ_FILES_MOUNTMAP may be in inconsistent state, contact Microsoft support ***"
+                eecho "*** [FATAL] MOUNTMAPv4 may be in inconsistent state, contact Microsoft support ***"
             fi
         fi
 
         if [ $ret -ne 0 ]; then
-            chattr -f +i $AZ_FILES_MOUNTMAP
-            eecho "[$1] failed to remove from ${AZ_FILES_MOUNTMAP}!"
+            chattr -f +i $MOUNTMAPv4
+            eecho "[$1] failed to remove from ${MOUNTMAPv4}!"
             return 1
         fi
-        chattr -f +i $AZ_FILES_MOUNTMAP
+        chattr -f +i $MOUNTMAPv4
 
         # Return the mtime after our mods.
-        echo $(stat -c%Y $AZ_FILES_MOUNTMAP)
-    ) 999<$AZ_FILES_MOUNTMAP
+        echo $(stat -c%Y $MOUNTMAPv4)
+    ) 999<$MOUNTMAPv4
 }
 
 #
 # Kill stunnel process and clean up stunnel files generated by aznfs mount helper
 #
-cleanupStunnelFiles()
+cleanup_stunnel_files()
 {
     local l_conf=$1
     local l_log=$2
@@ -460,11 +456,11 @@ cleanupStunnelFiles()
 # Watchdog for monitoring unmounts and more importantly change in blob endpoint
 # addresses possibly as a result of migration.
 #
-processNFS3Mounts()
+process_nfsv3_mounts()
 {
     #
     # TODO: Add a function reconcile_mountmap() and call it from here. This
-    #       should reconstruct the MOUNTMAP file from findmnt and output of
+    #       should reconstruct the MOUNTMAPv3 file from findmnt and output of
     #       iptables. This will be added in subsequent revisions.
     #
 
@@ -485,25 +481,25 @@ processNFS3Mounts()
     fi
 
     #
-    # Go over all lines in $MOUNTMAP and check them for two things:
+    # Go over all lines in MOUNTMAPv3 and check them for two things:
     # 1. Is that entry still in use by at least one aznfs mount, if not remove the entry.
     # 2. Has the Blob endpoint address changed from what is stored?
     #    If yes, update DNAT rule to point to the new address and update entry accordingly.
     #
-    # Sample line in $MOUNTMAP.
+    # Sample line in MOUNTMAPv3.
     # account.blob.preprod.core.windows.net 10.100.100.100 52.230.170.200
     #
     # where the format is
     # blobendpoint_fqdn proxy_ip blobendpoint_ip
     #
-    # We store the mtime of MOUNTMAP while inside the lock so that if any mount helper process
+    # We store the mtime of MOUNTMAPv3 while inside the lock so that if any mount helper process
     # updates it after this we will skip modification for sake of safety. We will come to it
     # in the next iteration when it's safer.
     #
-    exec {fd}<$MOUNTMAP
+    exec {fd}<$MOUNTMAPv3
     flock -e $fd
-    mtime_mountmap=$(stat -c%Y $MOUNTMAP)
-    IFS=$'\n' lines=$(cat $MOUNTMAP)
+    mtime_mountmap=$(stat -c%Y $MOUNTMAPv3)
+    IFS=$'\n' lines=$(cat $MOUNTMAPv3)
     flock -u $fd
     exec {fd}<&-
 
@@ -514,7 +510,7 @@ processNFS3Mounts()
     fi
 
     #
-    # Do unmount GC only if MOUNTMAP file is not modified in the last
+    # Do unmount GC only if MOUNTMAPv3 file is not modified in the last
     # MOUNTMAP_INACTIVITY_SECS seconds. We don't want to incorrectly delete an
     # entry while some aznfs mount is ongoing.
     #
@@ -526,8 +522,8 @@ processNFS3Mounts()
     fi
 
     #
-    # findmnt must be done after reading MOUNTMAP so that if we come accross a
-    # MOUNTMAP entry whose proxy_ip is not used by any existing mount, we know
+    # findmnt must be done after reading MOUNTMAPv3 so that if we come accross a
+    # MOUNTMAPv3 entry whose proxy_ip is not used by any existing mount, we know
     # for sure that it's not in use by any mount and can be removed.
     #
     findmnt=$(findmnt --raw --noheading -o MAJ:MIN,FSTYPE,SOURCE,TARGET,OPTIONS -t nfs 2>&1)
@@ -551,51 +547,51 @@ processNFS3Mounts()
         fi
 
         #
-        # MOUNTMAP line is of the form:
+        # MOUNTMAPv3 line is of the form:
         # account.blob.preprod.core.windows.net <local ip> <public ip> [<PID>]
         #
         IFS=" " read l_host l_ip l_nfsip <<< "$line"
 
         if [ -z "$l_host" -o -z "$l_ip" -o -z "$l_nfsip" ]; then
-            wecho "[FATAL] Deleting invalid line in $MOUNTMAP: [$line]!"
-            l_mtime=$(ensure_mountmap_not_exist "$line")
+            wecho "[FATAL] Deleting invalid line in $MOUNTMAPv3: [$line]!"
+            l_mtime=$(ensure_mountmapv3_not_exist "$line")
             [ $? -eq 0 ] && mtime_mountmap=$l_mtime
             continue
         fi
 
-        # Since we added it to the MOUNTMAP file, it cannot be invalid.
+        # Since we added it to the MOUNTMAPv3 file, it cannot be invalid.
         if ! is_private_ip "$l_ip"; then
             wecho "[FATAL] local ip ($l_ip) is invalid!"
-            l_mtime=$(ensure_mountmap_not_exist "$line")
+            l_mtime=$(ensure_mountmapv3_not_exist "$line")
             [ $? -eq 0 ] && mtime_mountmap=$l_mtime
             continue
         fi
 
-        # Since we added it to the MOUNTMAP file, it cannot be invalid.
+        # Since we added it to the MOUNTMAPv3 file, it cannot be invalid.
         if ! is_valid_ipv4_address "$l_nfsip"; then
             wecho "[FATAL] Blob endpoint ip ($l_nfsip) is invalid!"
-            l_mtime=$(ensure_mountmap_not_exist "$line")
+            l_mtime=$(ensure_mountmapv3_not_exist "$line")
             [ $? -eq 0 ] && mtime_mountmap=$l_mtime
             continue
         fi
 
         #
-        # Delete entry from MOUNTMAP if there are no mounted shares on that host.
-        # As long as we have at least one mount using the MOUNTMAP entry, we leave
+        # Delete entry from MOUNTMAPv3 if there are no mounted shares on that host.
+        # As long as we have at least one mount using the MOUNTMAPv3 entry, we leave
         # it around.
         #
         if ! echo "$findmnt" | grep " nfs ${l_ip}:" >/dev/null; then
             if $do_unmount_gc; then
-                pecho "No mounted shares for host $l_host, deleting from ${MOUNTMAP} [$line]."
+                pecho "No mounted shares for host $l_host, deleting from ${MOUNTMAPv3} [$line]."
 
                 # Delete IFF mountmap is not changed since we read it above.
-                l_mtime=$(ensure_mountmap_not_exist "$line" "$mtime_mountmap")
+                l_mtime=$(ensure_mountmapv3_not_exist "$line" "$mtime_mountmap")
 
                 #
-                # Update ifmatch time in case of successful updation of MOUNTMAP,
-                # so that we can distinguish between MOUNTMAP mtime changing because
+                # Update ifmatch time in case of successful updation of MOUNTMAPv3,
+                # so that we can distinguish between MOUNTMAPv3 mtime changing because
                 # of our action or some mount helper changing it. In the former case
-                # it's safe to update the MOUNTMAP, so update mtime_mountmap to the
+                # it's safe to update the MOUNTMAPv3, so update mtime_mountmap to the
                 # mtime after this update.
                 #
                 [ $? -eq 0 ] && mtime_mountmap=$l_mtime
@@ -604,7 +600,7 @@ processNFS3Mounts()
         else
             #
             # Verify that iptable entry should be present for corresponding
-            # MOUNTMAP entry if the share is not unmounted.
+            # MOUNTMAPv3 entry if the share is not unmounted.
             #
             # Note: This is extra protection in case user flushes the iptable
             #       entries or removes it by mistake. This should not be
@@ -645,15 +641,15 @@ processNFS3Mounts()
         # If we fail to resolve the host name, try next time.
         if [ $? -ne 0 ]; then
             #
-            # If account is deleted then we need to delete the MOUNTMAP entry along
+            # If account is deleted then we need to delete the MOUNTMAPv3 entry along
             # with the proxy iptable entry created for that account.
-            # Note that we don't delete if the MOUNTMAP was changed recently since
+            # Note that we don't delete if the MOUNTMAPv3 was changed recently since
             # the account may have been re-created after the dns lookup failure.
             #
             if [ "$new_ip" == "NXDOMAIN" ]; then
-                pecho "Account corresponding to $l_host seems to have been deleted, deleting from ${MOUNTMAP} [$line]!"
+                pecho "Account corresponding to $l_host seems to have been deleted, deleting from ${MOUNTMAPv3} [$line]!"
 
-                l_mtime=$(ensure_mountmap_not_exist "$line" "$mtime_mountmap")
+                l_mtime=$(ensure_mountmapv3_not_exist "$line" "$mtime_mountmap")
                 [ $? -eq 0 ] && mtime_mountmap=$l_mtime
             else
                 eecho "resolve_ipv4($l_host) failed: $new_ip"
@@ -670,7 +666,7 @@ processNFS3Mounts()
             check_for_regional_account "$l_host"
 
             # This will update DNAT rule as well.
-            if ! update_mountmap_entry "$line" "$l_host $l_ip $new_ip"; then
+            if ! update_mountmapv3_entry "$line" "$l_host $l_ip $new_ip"; then
                 eecho "Will reattempt the operation in next iteration."
             else
                 mountpoint2048=$(echo "$findmnt" 2>/dev/null | egrep -m1 " nfs ${l_ip}:.*\<port=2048\>" | awk '{print $4}')
@@ -686,7 +682,7 @@ processNFS3Mounts()
 #
 # Watchdog for monitoring unmounts and stunnel processes
 #
-processNFS4Mounts()
+process_nfsv4_mounts()
 {
     local l_host
     local l_conf
@@ -697,24 +693,24 @@ processNFS4Mounts()
     epoch_now=$(date +%s)
 
     #
-    # Go over all lines in $AZ_FILES_MOUNTMAP and check them for two things:
+    # Go over all lines in MOUNTMAPv4 and check them for two things:
     # 1. Is that entry still in use by at least one aznfs mount, if not remove the entry.
     # 2. Is stunnel process running?
     #
-    # We store the mtime of AZ_FILES_MOUNTMAP while inside the lock so that if any mount helper process
+    # We store the mtime of MOUNTMAPv4 while inside the lock so that if any mount helper process
     # updates it after this we will skip modification for sake of safety. We will come to it
     # in the next iteration when it's safer.
     #
-    exec {fd}<$AZ_FILES_MOUNTMAP
+    exec {fd}<$MOUNTMAPv4
     flock -e $fd
-    mtime_mountmap=$(stat -c%Y $AZ_FILES_MOUNTMAP)
-    IFS=$'\n' lines=$(cat $AZ_FILES_MOUNTMAP)
+    mtime_mountmap=$(stat -c%Y $MOUNTMAPv4)
+    IFS=$'\n' lines=$(cat $MOUNTMAPv4)
     flock -u $fd
     exec {fd}<&-
 
     #
-    # findmnt must be done after reading AZ_FILES_MOUNTMAP so that if we come accross a
-    # AZ_FILES_MOUNTMAP entry whose all nfs file shares are unmounted, we know
+    # findmnt must be done after reading MOUNTMAPv4 so that if we come accross a
+    # MOUNTMAPv4 entry whose all nfs file shares are unmounted, we know
     # for sure that it's not in use by any mount and can be removed.
     #
     findmnt=$(findmnt | grep 'nfs4\|$LOCALHOST' 2>&1)
@@ -738,14 +734,14 @@ processNFS4Mounts()
         fi
 
         #
-        # AZ_FILES_MOUNTMAP line is of the form:
+        # MOUNTMAPv4 line is of the form:
         # account.file.preprod.core.windows.net;<stunnel_account.file.preprod.core.windows.net.conf path>;<stunnel_account.file.preprod.core.windows.net.log path>;<stunnel_account.file.preprod.core.windows.net.pid path>;<checksumHash>
         #
         IFS=";" read l_host l_conf l_log l_pid l_checksumhash <<< "$line"
 
         if [ -z "$l_host" -o -z "$l_conf" -o -z "$l_pid" ]; then
-            wecho "[FATAL] Deleting invalid line in $AZ_FILES_MOUNTMAP: [$line]!"
-            l_mtime=$(ensure_az_files_mountmap_not_exist "$line")
+            wecho "[FATAL] Deleting invalid line in $MOUNTMAPv4: [$line]!"
+            l_mtime=$(ensure_mountmapv4_not_exist "$line")
             [ $? -eq 0 ] && mtime_mountmap=$l_mtime
             continue
         fi
@@ -754,23 +750,23 @@ processNFS4Mounts()
         vecho "accept_port: $accept_port"
 
         #
-        # Delete entry from AZ_FILES_MOUNTMAP if there are no mounted shares on that host.
-        # As long as we have at least one mount using the AZ_FILES_MOUNTMAP entry, we leave
+        # Delete entry from MOUNTMAPv4 if there are no mounted shares on that host.
+        # As long as we have at least one mount using the MOUNTMAPv4 entry, we leave
         # it around.
         #
         if ! echo "$findmnt" | grep "$accept_port" >/dev/null; then
-            pecho "No mounted shares for host $l_host, deleting from ${AZ_FILES_MOUNTMAP} [$line]."
+            pecho "No mounted shares for host $l_host, deleting from ${MOUNTMAPv4} [$line]."
 
-            cleanupStunnelFiles $l_conf $l_log $l_pid
+            cleanup_stunnel_files $l_conf $l_log $l_pid
 
             # Delete IFF mountmap is not changed since we read it above.
-            l_mtime=$(ensure_az_files_mountmap_not_exist "$line" "$mtime_mountmap")
+            l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
 
             #
-            # Update ifmatch time in case of successful updation of AZ_FILES_MOUNTMAP,
-            # so that we can distinguish between AZ_FILES_MOUNTMAP mtime changing because
+            # Update ifmatch time in case of successful updation of MOUNTMAPv4,
+            # so that we can distinguish between MOUNTMAPv4 mtime changing because
             # of our action or some mount helper changing it. In the former case
-            # it's safe to update the AZ_FILES_MOUNTMAP, so update mtime_mountmap to the
+            # it's safe to update the MOUNTMAPv4, so update mtime_mountmap to the
             # mtime after this update.
             #
             [ $? -eq 0 ] && mtime_mountmap=$l_mtime
@@ -789,10 +785,10 @@ processNFS4Mounts()
                 eecho "azfilenfs-watchdog service will do cleanup, kill stunnel process with pid:$(cat $l_pid) and remove '${l_conf}'; '${l_log}'; '${l_pid}'!"
                 eecho "Please remount the shares from ${l_host} using aznfs mount helper."
 
-                cleanupStunnelFiles $l_conf $l_log $l_pid
+                cleanup_stunnel_files $l_conf $l_log $l_pid
 
                 # Delete IFF mountmap is not changed since we read it above.
-                l_mtime=$(ensure_az_files_mountmap_not_exist "$line" "$mtime_mountmap")
+                l_mtime=$(ensure_mountmapv4_not_exist "$line" "$mtime_mountmap")
                 [ $? -eq 0 ] && mtime_mountmap=$l_mtime
                 continue
             fi
@@ -826,7 +822,6 @@ processNFS4Mounts()
     done
 }
 
-
 vecho "Starting aznfswatchdog..."
 
 # Detect and log distro, bash and AZNFS-mount version
@@ -843,21 +838,15 @@ if [ $? -eq 0 ] && [ -n "$conntrack_timeo_timew" -a $conntrack_timeo_timew -gt $
         echo $AZNFS_TIMEWAIT_TIMEOUT > /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_time_wait
 fi
 
-if ! chattr -f +i $MOUNTMAP; then
-    wecho "chattr does not work for ${MOUNTMAP}!"
+if ! chattr -f +i $MOUNTMAPv3; then
+    wecho "chattr does not work for ${MOUNTMAPv3}!"
 fi
 
 # For NFS V4 mount map file
-if [ ! -f $AZ_FILES_MOUNTMAP ]; then
-    touch $AZ_FILES_MOUNTMAP
-    if [ $? -ne 0 ]; then
-        eecho "[FATAL] Not able to create '${AZ_FILES_MOUNTMAP}'!"
-        exit 1
-    fi
-fi
+touch_mountmapv4
 
-if ! chattr -f +i $AZ_FILES_MOUNTMAP; then
-    wecho "chattr does not work for ${AZ_FILES_MOUNTMAP}!"
+if ! chattr -f +i $MOUNTMAPv4; then
+    wecho "chattr does not work for ${MOUNTMAPv4}!"
 fi
 
 #
@@ -871,9 +860,9 @@ fi
 
 while :; do
     sleep $MONITOR_INTERVAL_SECS
-    vecho "Processing NFSV3 mounts"
-    processNFS3Mounts
-    vecho "Processing NFSV4 mounts"
-    processNFS4Mounts
+    vecho "Processing NFSv3 mounts..."
+    process_nfsv3_mounts
+    vecho "Processing NFSv4 mounts..."
+    process_nfsv4_mounts
 done
 
